[core]
copyFrom:ROOT:地球联合政府/飞机/空军单位参考.ini,ROOT:unit-behaviors.template
name:奥卡攻击机
displayText:奥卡攻击机
displayText_ja:襲撃機：Orca
displayDescription:[固定翼飞机][反装甲/步兵]\n-早期的反装甲力量\n-航弹的溅射对步兵也有着不俗的杀伤
displayDescription_ja = [固定翼航空機] [反装甲/歩兵] \ n-hearly anti-armored power \ n-爆弾のスパッタは歩兵の良い殺害も持っています

price:500,机场位=1
mass:1000
buildSpeed:20s
maxHp:320
radius:10
energyStartingPercentage:1
energyMax:3
disableAllUnitCollisions:false
tags:plane,planes,Valid
fireTurretXAtSelfOnDeath:1

[graphics]
image:攻击机.png
scaleImagesTo:30
image_shadow:AUTO
drawLayer:top

[attack]
maxAttackRange:25
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
disablePassiveTargeting:true

[turret_1]
x:0
y:0
energyUsage:1
#aimOffsetSpread:0
shoot_sound:攻击音效.wav
canAttackCondition:true

[projectile_1]
life:100
areaDamage:320
areaRadius:40
speed:3
buildingDamageMultiplier:0.6
explodeEffect:CUSTOM:boom
color:#FFFFFF00
hitSound:true
trailEffect:true
lightSize:1
lightColor:#FFFFFF00
lightCastOnGround:true

[effect_boom]
alsoPlaySound:爆炸音效.wav


[movement]
movementType:AIR
moveSpeed:2.5
moveAccelerationSpeed:0.02
moveDecelerationSpeed:0
landOnGround:false
targetHeight:50
maxTurnSpeed:2
turnAcceleration:0.3
moveSlidingMode:false
slowDeathFall:true
joinsGroupFormations:false
reverseSpeedPercentage:0

[action_AI返航]
text:ai返航
displayType:action
buildSpeed:1
pos:0.1
autoTrigger:if not self.isAtGroundHeight and self.energy(lessThan=1) and self.isControlledByAI
isVisible:false
addWaypoint_type:loadInto

addWaypoint_target_nearestUnit_team:own
addWaypoint_target_nearestUnit_tagged:空载机场
clearAllWaypoints:true

[action_AI攻击]
text:AI攻击
displayType:action
buildSpeed:1
pos:0.1
autoTrigger:if self.energy(greaterThan=1) and self.isControlledByAI
isVisible:false
addWaypoint_type:attack

addWaypoint_target_nearestUnit_team:enemy
addWaypoint_target_nearestUnit_tagged:lives,tank
clearAllWaypoints:true



[action_speed]
text:加速
description:以血量为代价加速
isLocked:if self.hasFlag(id=2)
isLockedMessage:发动机已到最大功率
setUnitStats:movespeed+=2
addResources:speed=15,setFlag=2

[hiddenAction_loseHp]
autoTrigger:if self.resource(type='speed',greaterThan=0) and self.hasFlag(id=2)
setUnitStats:hp-=10
addResources:speed=-1
[hiddenAction_speedEnd]
autoTrigger:if self.resource(type='speed',lessThan=1) and self.hasFlag(id=2)
setUnitStats:movespeed-=2
addResources:unsetFlag=2
setResourcesWithLogic:speed=0

[global_resource_机场位]
displayName:机场位
displayRoundedDown:true

[resource_speed]
hidden:false
