[core]
name: 空军作战指挥部
copyFrom:ROOT:地球联合政府/建筑/建筑模板.ini,ROOT:unit-behaviors.template
price:4500
mass:114514
radius:30
maxHp:2300
armour:2
displayDescription:[建筑][支援科技]\n-为你提供以下强力的支援\n-允许建造世纪轰炸机,运输直升机,将轻型武装直升机升级\n-获得支援技能 空运 将9个步兵送到指定位置\n-获得支援技能 侦察 暂时打开指定位置视野\n-获得支援技能 王牌空军 回复范围内空军能量 加快其速度并增加其护甲以使其获得更好的突防能力\n-获得支援技能 奥卡轰炸 派遣一架无法被攻击的奥卡攻击机对指定位置造成一定的伤害
displayDescription_ja = [アーキテクチャ] [サポートテクノロジー] \ nは、1世紀の爆撃機、輸送ヘリコプター、ライトアーム付きヘリコプターのアップグレード - 指定された位置ビジョンを一時的に開くために、1世紀の爆撃機、輸送ヘリコプターを構築するために、次の強力なサポートを使用してあなたをプロバイします。空軍エネルギーはその速度を加速し、サポートスキルのリターン範囲でその鎧を増やします空軍はより良い能力を得るために攻撃できないOKA攻撃航空機を送信します。
isBuilding:true
footprint:-1,-1,1,1
constructionFootprint:-1,-1,1,1
energyMax:1
energyStartingPercentage:0
energyRegen:0.0002
buildSpeed:60s
tags:t2_tech,空军作战指挥部,Valid
maxTransportingUnits:9
transportUnitsRequireTag:lives


[graphics]
image:空军作战指挥部.png
scaleImagesTo:70
total_frames:2


[attack]
canAttack:false
maxAttackRange:114514

[turret_1]
x:0
y:0
image:NONE

[projectile_1]
directDamage:0
life:100000
speed:5
image:战斗机.png
unloadUpToXUnitsFromSource:9


[turret_2]
x:0
y:0
image:NONE
projectile:2

[projectile_2]
spawnUnit:视野

directDamage:0
life:100000
speed:1000
explodeEffect:1

[turret_3]
x:0
y:0
image:NONE
projectile:3

[projectile_3]
areaDamage:0
areaRadius:240
targetGround:false
targetGround_includeTargetHeight:true
mutatorX_ifUnitWithTags:plane
mutatorX_addResourcesAreaHit:hormor=30
friendlyFire:true
areaHitAirAndLandAtSameTime:true

life:100000
speed:1000

[turret_4]
x:0
y:0
image:NONE
projectile:4

[projectile_4]
areaDamage:300
areaRadius:20
targetGround:false
friendlyFire:true
explodeEffect:1
life:100000
speed:1000


[effect_1]
life:200
alwayStartDirAtZero:true
xOffsetAbsolute:-200
yOffsetAbsolute:-200
xSpeedAbsolute:2
ySpeedAbsolute:2
image:战斗机.png
fadeInTime:60
fadeOut:true
dirOffset:45

[resource_hormor]
hidden:true

[action_trans]
text:空运

description:空运九个单位到指定位置
price:energy=1,1200
fireTurretXAtGround:1
onlyOneUnitAtATime:true

[action_1]
text:侦察
description:派出一架侦察机打开小范围内的视野
price:energy=0.5,200
fireTurretXAtGround:2
onlyOneUnitAtATime:true
[action_2]
text:王牌空军
description:暂时性加强范围内的空军单位(对载具内单位无影响)
price:energy=0.7,900
fireTurretXAtGround:3
buildSpeed:0s
onlyOneUnitAtATime:true
[action_3]
text:奥卡轰炸
description:召唤一架奥卡，干扰一下对手
price:energy=0.2,200
fireTurretXAtGround:4
buildSpeed:0s
onlyOneUnitAtATime:true
#alsoQueueAction

#[action_3_1]
#text:奥卡轰炸2
#description:召唤一架奥卡，干扰一下对手
#fireTurretXAtGround:5
#buildSpeed:2s


[movement]
movementType:BUILDING

[leg_1]
x:15
y:15
attach_x:15
attach_y:15
image_foot:雷达.png
drawOverBody:false
[ai]
buildPriority:0.15
noneInBaseExtraPriority:0.53
recommendedInEachBaseNum:1
recommendedInEachBasePriorityIfUnmet:0.53
maxEachBase:2
[animation_1]
onActions:idle
leg1_0:{x:-5,y:0}
leg1_10s:{x:-15,y:0}
leg1_20s:{x:-5,y:0}

body_0:{frame:0}
body_0.2s:{frame:0}
body_0.4s:{frame:1}
body_0.6s:{frame:1}
body_0.8s:{frame:1}
body_1s:{frame:1}

body_1.2s:{frame:0}
body_1.4s:{frame:1}
body_1.6s:{frame:1}
body_1.8s:{frame:1}
body_2s:{frame:1}

body_2.2s:{frame:0}
body_2.4s:{frame:1}
body_2.6s:{frame:1}
body_2.8s:{frame:1}
body_3s:{frame:1}

body_3.2s:{frame:0}
body_3.4s:{frame:1}
body_3.6s:{frame:1}
body_3.8s:{frame:1}
body_4s:{frame:1}

body_4.2s:{frame:0}
body_4.4s:{frame:1}
body_4.6s:{frame:1}
body_4.8s:{frame:1}
body_5s:{frame:1}

body_5.2s:{frame:0}
body_5.4s:{frame:1}
body_5.6s:{frame:1}
body_5.8s:{frame:1}
body_6s:{frame:1}

body_6.2s:{frame:0}
body_6.4s:{frame:1}
body_6.6s:{frame:1}
body_6.8s:{frame:1}
body_7s:{frame:1}

body_7.2s:{frame:0}
body_7.4s:{frame:1}
body_7.6s:{frame:1}
body_7.8s:{frame:1}
body_8s:{frame:1}

body_8.2s:{frame:0}
body_8.4s:{frame:1}
body_8.6s:{frame:1}
body_8.8s:{frame:1}
body_9s:{frame:1}

body_9.2s:{frame:0}
body_9.4s:{frame:1}
body_9.6s:{frame:1}
body_9.8s:{frame:1}
body_10s:{frame:1}

body_10.2s:{frame:0}
body_10.4s:{frame:1}
body_10.6s:{frame:1}
body_10.8s:{frame:1}
body_11s:{frame:1}
