[core]
copyFrom:ROOT:SPARK/SPARK.template,ROOT:unit-behaviors.template


name:SPARK T1飞弹机器人

displayText:T1飞弹机器人
displayDescription:[对地/空][T1][陆地]\n前期的廉价机器人\n可以对空对地,早期支援防空火力
price:0
mass:2000
maxHp:300
tags:T1,Tech1MissleBot,Valid
radius:7
buildSpeed:30s

[graphics]
#image:SPARK T1战斗机器人c.png
image:SPARK T1战斗机器人主体.png
scaleImagesTo:20
image_shadow:SHADOW:SPARK T1飞弹机器人.png
image_wreak:SPARK T1战斗机器人残骸.png

shadowOffsetX:1
shadowOffsetY:1
teamColorsOnTurret:true

image_turret:SPARK T1飞弹机器人.png
scaleTurretImagesTo:20
lock_body_rotation_with_main_turret:true

[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:120
turretMultiTargeting:false


[turret_1]
x:0
y:0

shoot_sound:missile_fire

recoilOffset:-2
recoilOutTime:4
recoilReturnTime:30



idleSweepSpeed:0.3
idleSweepAngle:60
idleSweepDelay:180
idleSweepAddRandomDelay:100
idleSweepAddRandomAngle:20
idleSweepCondition:if not self.isMoving()
delay:180
aimOffsetSpread:0.1



barrelX:5
barrelY:5

[turret_2]
x:0
y:0
image:NONE.png
barrelX:-5
copyFrom:1
delay:180


[projectile_1]
directDamage:45
life:100
frame:4
drawSize:0.5
speed:1
targetSpeedAcceleration:0.1
targetSpeed:6
lightSize:0.8
lightColor:#FF882200
buildingDamageMultiplier:0.4
trailEffect:true
mutator1_ifUnitWithTags:tank
mutator1_directDamageMultiplier:2
[movement]
movementType:LAND
moveSpeed:0.4

moveAccelerationSpeed:0.1
moveDecelerationSpeed:0.1

maxTurnSpeed:5
turnAcceleration:8
moveIgnoringBody:true
reverseSpeedPercentage:0


[leg_1]
x: -4
y: 4
endDirOffset:225
attach_x:-0
attach_y:0
moveSpeed: 2
resetAngle:225
dust_effect:false
image_leg:  足c.png

holdDisMin:0.5
holdDisMax:2
hardLimit:5
holdDisMin_checkNeighbours:true
favourOppositeSideNeighbours:true
estimatingPositionMultiplier:0.2

#image_foot: foot1.png

[leg_2]
copyFrom:1
attach_x:0
attach_y:0
x:4
y:4
image_leg:足c.png
#dust_effect:true
[leg_3]
copyFrom:1
attach_x:-0
attach_y:-0
x:-4
y:-4
#dust_effect:true
image_leg:足c.png
[leg_4]
attach_x:0
attach_y:-0
copyFrom:1
x:4
y:-4
image_leg:足c.png


[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=300
