
[core]
copyFrom:ROOT:SPARK/SPARK.template,ROOT:templete/SPARK_factory.ini,ROOT:unit-behaviors.template
@global ableToAddBuildSpeed:0
nanoFactorySpeed:1.5
showActionsWithMixedSelectionIfOtherUnitsHaveTag:bulitaryBuilding

name:T1 SPARK机器人工厂
displayText:T1 SPARK机器人工厂
displayDescription:[工厂][T1][建筑]\n用于生产四足机器人的工厂\n拥有简易护甲\n-自身「馈赠」足够时可以提升科技等级\n-在未达到工厂数量上限时,可消耗「馈赠」提升生产速度
buildSpeed:30s
borrowResourcesWhileBuilt:maxFactories=1
price:0
radius:30
tags:produceBuildings,bulitaryBuilding,Valid
mass:10000
isBuilding:true
maxHp:2000
armour:5
footprint:0,0,1,1
constructionFootprint:-1,-1,2,3
buildingToFootprintOffsetX:20
canBuild_1_name:setRally
canBuild_1_pos:0
maxTransportingUnits:4
transportUnitsRequireTag:technology
transportUnitsBlockOtherTransports:false
transportUnitsBlockAirAndWaterUnits:false
transportUnitsRequireMovementType:HOVER

defineUnitMemory:float nanoBuildSpeedMemory

@memory resourceBuilding:unit[]






[hiddenAction_addTechGrade]
autoTrigger:if self.resource.Gift>1000 or self.transportingCount(greaterThan=3)
deleteNumUnitsFromTransport:4

convertTo:T2 SPARK机器人工厂
addResources:Gift=-1000
[graphics]
image:SPARK机器人工厂.png
scaleImagesTo:70


[canBuild_2]
pos:1
name:SPARK T1 建造者

[canBuild_3]
pos:2
name:SPARK T1战斗机器人

[canBuild_4]
pos:3
name:SPARK T1飞弹机器人

[canBuild_5]
pos:4
name:SPARK T1飞行机器人

[canBuild_6]
pos:5
name:SPARK T2升级核心



[ai]
buildPriority:0.8
noneInBaseExtraPriority:1
noneGlobalExtraPriority:1
recommendedInEachBaseNum:20
maxGlobal:100

#[action_1]
#pos:0
#text:%{memory.nanoBuildSpeedMemory+(memory.resourceBuilding.size)*(0.2)}
#deleteSelf:true
#displayType:infoOnly




[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=1000

[action_stop]
text:工厂维护
pos:0.1
isVisible:if not self.hasFlag(id=31)
description:暂时停止工厂以使其余工厂恢复生产
addResources:setFlag=31,maxFactories=1
buildSpeed:0s
setUnitStats:nanoFactorySpeed=0.01
highPriorityQueue:true
onlyOneUnitAtATime:true
displayType:action
iconImage:ROOT:/shared/错误.png

[action_unstop]
text:工厂开工
pos:0.1
isVisible:if self.hasFlag(id=31)
description:启动工厂工厂以恢复生产
addResources:unsetFlag=31,maxFactories=-1
setUnitStats:nanoFactorySpeed=0.2
buildSpeed:0s
highPriorityQueue:true
displayType:action


[hiddenAction_massEffect]
autoTrigger:if self.resource.Gift>100
spawnEffects:CUSTOM:massGiven

#[hiddenAction_addnanoByGift]
#autoTrigger:if self.hp()==self.maxHp() and self.resource.Gift>100
#setUnitStats:nanoFactorySpeed+=0.1
#addResources:Gift=-100



