
[core]
copyFrom:ROOT:SPARK/SPARK.template,ROOT:templete/SPARK_factory.ini,ROOT:unit-behaviors.template

nanoFactorySpeed:2
showActionsWithMixedSelectionIfOtherUnitsHaveTag:bulitaryBuilding

name:T2 SPARK机器人工厂
displayText:T2 SPARK机器人工厂
displayDescription:[工厂][无法攻击][T2][建筑]\n用于生产更高级单位的工厂\n拥有简易护甲\n-在未达到工厂数量上限时,可消耗「馈赠」提升生产速度
buildSpeed:360s
price:0
borrowResourcesWhileBuilt:maxFactories=1
radius:30
tags:produceBuildings,bulitaryBuilding,Valid
mass:10000
isBuilding:true
maxHp:2500
armour:5
footprint:0,0,1,1
constructionFootprint:-1,-1,2,3
buildingToFootprintOffsetX:20
canBuild_1_name:setRally
canBuild_1_pos:0
maxTransportingUnits:4
transportUnitsRequireTag:technology
transportUnitsBlockOtherTransports:false
transportUnitsBlockAirAndWaterUnits:false
transportUnitsRequireMovementType:HOVER
defineUnitMemory:float nanoBuildSpeedMemory
#[hiddenAction_addTechGrade]
#autoTrigger:if self.resource.Gift>2000


[graphics]
image:SPARK机器人工厂t2.png
scaleImagesTo:70

[attack]
canAttack:false

[movement]
movementType:BUILDING

[canBuild_2]
pos:1
name:SPARK T1 建造者

[canBuild_3]
pos:2
name:SPARK T1战斗机器人

[canBuild_4]
pos:3
name:SPARK T1飞弹机器人

[canBuild_5]
pos:4
name:SPARK T1飞行机器人

[canBuild_6]
pos:5
name:SPARK T2升级核心

[canBuild_7]
pos:6
name:SPARK T2镭射机器人

[canBuild_8]
pos:7
name:SPARK T2等离子机器人


[ai]
buildPriority:0.8
noneInBaseExtraPriority:1
noneGlobalExtraPriority:1
recommendedInEachBaseNum:20
maxGlobal:100



[hiddenAction_群体检测]
autoTrigger:true
takeResources_searchOnly:true
takeResources_includeUnitsWithinRange_team:own
takeResources_includeUnitsWithinRange:300
takeResources_maxUnits:1000
takeResources_triggerActionForEach:add
takeResources_excludeUnitsWithoutTags:oil
#setUnitMemory:resourceBuilding[]=[]

[hiddenAction_add]
requireConditional:if not memory.resourceBuilding.contains(thisActionTarget)
setUnitMemory:resourceBuilding[memory.resourceBuilding.size]=thisActionTarget
#单位数组
shrinkArrays:resourceBuilding


[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=2000


[action_stop]
text:工厂维护
pos:0.1
isVisible:if not self.hasFlag(id=31)
description:暂时停止工厂以使其余工厂恢复生产
addResources:setFlag=31,maxFactories=1
buildSpeed:0s
setUnitStats:nanoFactorySpeed=0.01
highPriorityQueue:true
onlyOneUnitAtATime:true
displayType:action
iconImage:ROOT:/shared/错误.png

[action_unstop]
text:工厂开工
pos:0.1
isVisible:if self.hasFlag(id=31)
description:启动工厂工厂以恢复生产
addResources:unsetFlag=31,maxFactories=-1
setUnitStats:nanoFactorySpeed=0.2
buildSpeed:0s
highPriorityQueue:true
displayType:action


[hiddenAction_massEffect]
autoTrigger:if self.resource.Gift>100
spawnEffects:CUSTOM:massGiven

#[hiddenAction_addnanoByGift]
#autoTrigger:if self.hp()==self.maxHp() and self.resource.Gift>100
#setUnitStats:nanoFactorySpeed+=0.1
#addResources:Gift=-100



