[core]
name: 石油分馏厂
displayText:石油分馏厂

copyFrom:ROOT:SPARK/SPARK.template,ROOT:unit-behaviors.template
price:0
mass:114514
radius:30
buildSpeed:80s
maxHp:1200
armour:1
displayDescription:[建筑][回收]\n-可以回收地表裸露的油桶以加速周围工厂(必须手动回收!)\n-可以回收各种建筑或单位
displayDescription_ja = [アーキテクチャ] [リサイクル] \ n-リソースをリサイクルできる露出したオイルバレル（手動で回収する必要があります！）\ n-canリサイクルさまざまな建物またはユニット
tags:resourcesBUildings,Valid
isBuilding:true
footprint:-1,-1,1,1
constructionFootprint:-1,-1,1,1
#extraBuildRangeWhenBuildingThis:200

canRepairBuildings: true
canRepairUnits : true
autoRepair: true

nanoRepairSpeed: 0.1
canRepairUnitsOnlyWithTags:YouShouldNotFounddIt
canReclaimResources: true

nanoRange: 240
nanoBuildSpeed: 2
nanoReclaimSpeed:2

[canBuild_canReclaim]
name: reclaim
pos:  -1


[turret_1]
x:0
y:0
image:NONE


[projectile_1]
life:100    
speed:100
directDamage:0
deflectionPower:-1
instant:true
image:NONE


[hiddenAction_1]
autoTrigger:if self.hasActiveWaypoint(type='reclaim')
temporarilyAddTags:oil
spawnEffects:CUSTOM:smoke*1

[hiddenAction_2]
autoTrigger:if not self.hasActiveWaypoint(type='reclaim')
temporarilyRemoveTags:oil

[effect_smoke]
life:360
alsoEmitEffects:smoke
alpha:0.7
xOffsetRelative:-13
yOffsetRelative:15
lifeRandom:100

xOffsetRelativeRandom:2
yOffsetRelativeRandom:2
xSpeedRelativeRandom:0.1
ySpeedRelativeRandom:0.1
hSpeed:0.2
color:#AA000099

fadeOut:true
scaleTo:1
scaleFrom:0






[graphics]
image:石油分馏厂.png
total_frames:1
scaleImagesTo:70

[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=400


[attack]
canAttack:false


[movement]
movementType:BUILDING

