[core]
name              : SPARK T1对地防御塔
tags:Valid
displayText:SPARK T1对地防御塔
displayText_ja:SPARK T1機関銃座
displayDescription: [建筑][对地]\n-不错的初期对地单位\n-不要将它暴露在重型单位直射火力下!\n-建造会消耗过多的质量导致建造者被摧毁,请务必小心啊!
selfBuildRate:30s

copyFrom:ROOT:SPARK/SPARK.template,ROOT:unit-behaviors.template
price:400
mass:114514
radius:10
isBio:false
isBug:false
isBuilder:false
transportUnitsKillOnDeath:false
armour:20
maxHp:1600
buildSpeed:30s

isBuilding:true
footprint:0,0,0,0
constructionFootprint:0,0,0,0

[graphics]
image:ROOT:/SPARK/SPARK防御塔/SPARK T1防御塔/STARK T1轻型炮塔基座.png
image_turret:轻型炮塔.png
image_shadow:SHADOW:ROOT:/SPARK/SPARK防御塔/SPARK T1防御塔/STARK T1轻型炮塔基座.png
shadowOffsetX:2
shadowOffsetY:2
teamColorsOnTurret:true


[attack]
maxAttackRange:190
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
showRangeUIGuide:1

[turret_2]
x:0
y:10
slave:true
attachedTo:1
barrelOffsetX_onOddShots:1
recoilOffset:-2
recoilOutTime:2
recoilReturnTime:10
shoot_sound:开火音效.wav
delay:60
image:电浆炮管.png

[turret_1]
x:0
y:0
canAttack:false
idleSpin:0.2
turnSpeed:2


[projectile_1]
life:100
directDamage:140
mutatorX_ifUnitWithTags:lives
mutatorX_directDamageMultiplier:1.5
speed:15
image:抛射体1.png
drawSize:0.65
explodeEffect:small
lightSize:0.3
lightColor:#AAFFAAAA
trailEffect:CUSTOM:weiyan
trailEffectRate:0.01

[effect_weiyan]
life:20
image:狙击枪尾焰.png
attachedToUnit:false
alpha:0.3
color:#AAFF9999

[movement]
movementType:BUILDING


#[ai]
#buildPriority:0.1
#noneInBaseExtraPriority:0.53
#recommendedInEachBaseNum:5
#recommendedInEachBasePriorityIfUnmet:0.29
#maxEachBase:17

[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=800


[decal_target]
image:ROOT:/shared/at.png
layer:onTop
alpha:0.6
xOffsetAbsolute:10
yOffsetAbsolute:-10
onlyWhileAlive:true

[ai]
useAsAttacker:true
buildPriority:0.40
recommendedInEachBaseNum:10
upgradedFrom:SPARK T1 建造者



