[core]
copyFrom:ROOT:SPARK/SPARK.template,ROOT:unit-behaviors.template


name:SPARK T2镭射机器人

displayText:T2镭射机器人
displayDescription:[对地][T2][陆地]\中期的反装甲机器人\n火力凶猛,射程较远,但是孱弱的血量使其无法对抗任何防御建筑
price:0
mass:3000
maxHp:280
tags:Tech1GunRobot,Valid
radius:7
buildSpeed:40s

[graphics]
#image:SPARK T1战斗机器人c.png
image:SPARK T1战斗机器人主体.png
scaleImagesTo:20
image_shadow:SHADOW:SPARK T2镭射机器人c.png
image_wreak:SPARK T1战斗机器人残骸.png

shadowOffsetX:1
shadowOffsetY:1
teamColorsOnTurret:true

image_turret:SPARK T2镭射机器人c.png
scaleTurretImagesTo:20
lock_body_rotation_with_main_turret:true

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 20
turretTurnSpeed: 3


maxAttackRange: 135
shootDelay: 90

turretRotateWithBody: false

[turret_mainBody]
x: 0
y: 0
idleDir:0

barrelX: 5
barrelY: 8



turnSpeed: 2.9
turnSpeedAcceleration: 0.3

#canShoot: false


#note: lock_body_rotation_with_main_turret is needed for recoil to work on the body
recoilOffset: -1
recoilOutTime: 2
recoilReturnTime: 14


projectile: 1


shoot_sound:plasma_fire
shoot_sound_vol:0.03
#shoot_flame:small
#shoot_light:#FFccCCEE
shoot_flame:CUSTOM:lightSlowFade

canShoot: true


#energyUsage: 1
warmup:2
#chargeEffectImage: SHARED:lighting_charge.png
chargeEffectImage: SHARED:lighting_charge.png




idleSweepAngle:20
idleSweepSpeed:0.30
idleSweepDelay:100
idleSweepAddRandomDelay:50
idleSweepCondition: if not self.isMoving()
aimOffsetSpread:0





[turret_mainBody2]
x: 0
y: 0
idleDir:0

barrelX: -5
barrelY: 8



turnSpeed: 2.9
turnSpeedAcceleration: 0.3

#canShoot: false


#note: lock_body_rotation_with_main_turret is needed for recoil to work on the body
recoilOffset: -1
recoilOutTime: 2
recoilReturnTime: 14


projectile: 1


shoot_sound_vol:1
#shoot_flame:small
#shoot_light:#FFccCCEE
shoot_flame:CUSTOM:lightSlowFade

canShoot: true


#energyUsage: 1
warmup:2
#chargeEffectImage: SHARED:lighting_charge.png
chargeEffectImage: SHARED:lighting_charge.png




idleSweepAngle:20
idleSweepSpeed:0.30
idleSweepDelay:100
idleSweepAddRandomDelay:50
idleSweepCondition: if not self.isMoving()
aimOffsetSpread:0
shoot_sound        : 辐射.wav





[effect_lightSlowFade]
image: SHARED:light_50.png
life: 20
fadeOut: true
attachedToUnit: true
#color: #63e6e8
color: #FFEE0000
scaleFrom: 0.2
scaleTo: 0.5
alpha: 0.5
drawUnderUnits:true


[projectile_1]
directDamage: 40
life: 10
color:#AA770000
instant:true
laserEffect:true
deflectionPower:-1
lightSize:1
lightColor:#AA0000
lightCastOnGround:true

frame: 11

drawSize: 0.7




#speed: 2
speed: 0
targetSpeed: 8
targetSpeedAcceleration: 1.5

effectOnCreate: CUSTOM:projectileLight




[effect_projectileLight]
priority:high

image: SHARED:light_50.png
life: 100
fadeOut: true
attachedToUnit: true
color: #FFEECCCC
fadeInTime:2
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.6
drawUnderUnits:false
liveAfterAttachedDies: false
[movement]
movementType:LAND
moveSpeed:0.45

moveAccelerationSpeed:0.1
moveDecelerationSpeed:0.1

maxTurnSpeed:5
turnAcceleration:8
moveIgnoringBody:true
reverseSpeedPercentage:0


[leg_1]
x: -4
y: 4
endDirOffset:225
attach_x:-0
attach_y:0
moveSpeed: 2
resetAngle:225
dust_effect:false
image_leg:  足c.png

holdDisMin:0.5
holdDisMax:2
hardLimit:5
holdDisMin_checkNeighbours:true
favourOppositeSideNeighbours:true
estimatingPositionMultiplier:0.2

#image_foot: foot1.png

[leg_2]
copyFrom:1
attach_x:0
attach_y:0
x:4
y:4
image_leg:足c.png
#dust_effect:true
[leg_3]
copyFrom:1
attach_x:-0
attach_y:-0
x:-4
y:-4
#dust_effect:true
image_leg:足c.png
[leg_4]
attach_x:0
attach_y:-0
copyFrom:1
x:4
y:-4
image_leg:足c.png

[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=500

[hiddenAction_addAttackDamage]
autoTrigger:true
setUnitStats:shootDamageMultiplier=0.02* (self.maxHp()-self.hp())+1
