[core]

name: 居民楼1
tags:Valid

displayDescription:[建筑][可驻军]
maxHp:2000
mass:114514
price:0
radius:20
stayNeutral:true
createNeutral:true

isBuilding:true
footprint:-1,-1,1,1
constructionFootprint:-1,-1,1,1
maxTransportingUnits:6
buildSpeed:60s
selfBuildRate:60s
transportUnitsRequireTag:T1,lives
isUnrepairableUnit:true
whileNeutralTransportAnyTeam:true
whileNeutralConvertToTransportedTeam:true
convertToNeutralIfNotTransporting:true
transportUnitsKillOnDeath:true



armour:1

[hiddenAction_created]
autoTriggerOnEvent:created
switchToNeutralTeam:true




[graphics]
#图像节需要设置主体图像
image:居民楼1.png
scaleImagesTo:80
image_shadow:SHADOW:居民楼1.png
shadowOffsetX:2 
shadowOffsetY:2 


[attack]
canAttack:true
canAttackLandUnits:true
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
turretRotateWithBody:false
turretTurnSpeed:30
attackMovement:normal
maxAttackRange:140
shootDelay:2
isFixedFiring:false

[attachment_1]
x=-10
y=10
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true

[attachment_2]
x=-10
y=0
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true


[attachment_3]
x=-10
y=-10
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true

[attachment_4]
x=10
y=10
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true

[attachment_5]
x=10
y=0
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true

[attachment_6]
x=10
y=-10
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true

[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=300



[movement]
movementType:BUILDING
