[core]

name: 特斯拉电塔
copyFrom:ROOT:地球联合政府/建筑/建筑模板.ini
displayDescription:[建筑][先进反装甲]\n-最好的反装甲防御塔\n-可以使地方装甲单位无法移动
displayDescription_ja = [アーキテクチャ] [Advanced Anti-Armor] \ n-The Best Anti-Armor Defense Tower \ n-Canは、地元の装甲ユニットを移動できないようにします
maxHp:1100
mass:114514
price:800
radius:13
buildSpeed:15s
#此模板在"基础模板"上修改
isBuilding:true
#此代码规定建筑范围
footprint:-1,0,1,1
constructionFootprint:-1,0,1,1

armour:3

[graphics]
#图像节需要设置主体图像
image:特斯拉电塔.png
image_turret:NONE
scaleImagesTo:50

[attack]
canAttack:true
canAttackLandUnits:true
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
turretRotateWithBody:false
turretTurnSpeed:114514
attackMovement:normal
maxAttackRange:205
shootDelay:1
isFixedFiring:false



[turret_1]


shouldResetTurret:true

#复制自_1
canAttack:true
canAttackLandUnits:true
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
x:0
y:20
idleDir:0
shoot_sound:lighting_burst
clearTurretTargetAfterFiring:true


[projectile_1]
image:NONE
tags:flash
shouldRevealFog:true
lightingEffect:true

directDamage:10
life:10
speed:13
trailEffect:false
lightColor:#FFFFFF
mutatorX_ifUnitWithTags:tank
mutatorX_directDamageMultiplier:5
mutatorX_addResourcesDirectHit:stop=1
instantReuseLast:true
instant:true

[action_update]
text:特斯拉电塔_散射升级
description:使攻击电流在击中目标之后会产生散射\n-同时增大了其射程
convertTo:特斯拉电塔_散射升级
price:400
isVisible:if self.hasUnitInTeam(withTag='磁暴塔',greaterThan=0)




[movement]
movementType:BUILDING

[resource_stop]
hidden:true
