[core]
copyFrom:ROOT:地球联合政府/坦克/装甲单位模板.ini,ROOT:unit-behaviors.template
name:58中坦
displayText:58式中型坦克
displayDescription:[装甲][对地][反装甲]\n-量产型中型坦克 是中期的主战炮灰\n-也许反装甲火力比它还要金贵
displayDescription_ja = [アーマー] [配信] [アンチアーマー] \ n-mass生産ミディアムタンクは、中時代の主要なバトルキャノン飼料です\ n-おそらくアンチアモルド火力はそれよりも高価です
mass:5000
price:1200
maxHp:2000
radius:16
softCollisionOnAll:1
buildSpeed:45s
maxTransportingUnits:0
armour:3
transportSlotsNeeded:4

[graphics]
image:58式.png

scaleImagesTo:22
dustEffect:true
total_frames:2
turretImageScale:1.1
animation_moving_start:0
animation_moving_end:1
animation_moving_speed:5

[attack]
maxAttackRange:155
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
showRangeUIGuide:true

#[turret_1]
#image:坦克炮塔.png
#x:0
#y:0
#shoot_sound:missile_fire
#shoot_light:#FF000000
#recoilOffset:-3
#recoilOutTime:2
#recoilReturnTime:10
#delay:60
#
#[projectile_1]
#image:抛射体.png
#life:100
#speed:1
#directDamage:100
#color:#FFAAAAAA
#drawSize:0.5
#lightSize:1
#lightCastOnGround:true
#lightColor:#FFAA0000

[turret_2]
image:58炮管.png
x:0
y:10
shoot_sound:tank_firing
shoot_light:#FF000000
recoilOffset:-3
recoilOutTime:2
recoilReturnTime:45
attachedTo:1
slave:1
delay:120


[turret_1]
image:58炮塔.png
x:0
y:-2
canShoot:false

shoot_light:#33000000
recoilOffset:-2
recoilOutTime:2
recoilReturnTime:45
turnSpeed:3

[projectile_1]
image:抛射体1.png
life:30
directDamage:500
areaDamageNoFalloff:true
color:#FFAAAAAA
drawSize:0.5

speed:16
trailEffect:true

largeHitEffect:true

lightColor:#ffff00
lightSize:0.2
buildingDamageMultiplier:0.7

[movement]
movementType:LAND
moveSpeed:1
moveAccelerationSpeed:10
moveDecelerationSpeed:1.12
reverseSpeedPercentage:0.5
maxTurnSpeed:4
turnAcceleration:1.35
moveSlidingMode:1
