[core]
copyFrom   : ROOT:地球联合政府/步兵/t1步兵基础/t1步兵基础.ini,ROOT:unit-behaviors.template
name       : 游击队员
displayText: 游击队员
displayDescription:[对地][反步兵][反建筑]\n-拥有丰富实战经验的游击队员,使用燃烧瓶作为主要武器\n-可以放置炸弹\n-不会被主动攻击\n-可以短暂的在敌人之前隐藏自己
maxHp:1000
price:600,hero=1
defineUnitMemory:float maxAttackRange
tags:lives,hero,游击队员,Valid

[core]
energyMax:1
energyRegen:0.000416
selfRegenRate     : 1
showOnMinimapToEnemies:false

[graphics]
image_turret:燃烧瓶inHand.png
turretImageScale:1

[action_hide]
text:隐藏
description:将自身隐藏为平民 无法攻击但也不会被敌人攻击
convertTo:游击队员_hide
buildSpeed:0s

[action_1]
text:包扎
description:治疗一下自身\n-这需要一点时间
addResources:hp=500
price:energy=0.5
buildSpeed:0.3s

[action_putBoob]
text       : 放置炸弹
description: 放置一枚威力巨大的炸弹, 对各种单位都有很好的毁伤效果\n但要是爆炸前就被敌人摧毁就不好了
description_ja:1個$50の梱包爆薬を置く。複数人で投げ込めば強化バンカーでもひとたまりもない
iconImage:雷管.png
price      : 50,energy=0.2
fireTurretXAtGround:boom
buildSpeed:0.2s

[turret_boom]
x:0
y:0
image:空.png
projectile:boom
canShoot:false

[projectile_boom]
directDamage:0
life:100000
speed:5
image:雷管.png
targetGround:true
spawnUnit:雷管

[action_hideP]
text:躲避
description:完全不可被地方发现
convertTo:游击队员_hideP
buildSpeed:0s
price:energy=1


[attack]
maxAttackRange:140
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
showRangeUIGuide:true
#isMelee:true
#meleeEngangementDistance:${attack.maxAttackRange}


[turret_1]
x:0
y:5

shoot_light:#FFAA0000
recoilOffset:3
recoilOutTime:2
recoilReturnTime:10
delay:60
projectile:1



[projectile_1]
life:1000
areaDamage:120
areaRadius:30
ballistic:true
shadowImage:SHADOW:燃烧瓶.png

drawSize:1
lightColor:#AAFF9966
#speed:2


speedSpread:0.2
speed:5
trueGravity:0.1
ballistic_delaymove_height:0

wobbleAmplitude:0.2
ballistic_height:10
turnSpeedWhenNear:0.001
explodeEffect:smoke
image:燃烧瓶.png

lightSize:1

lightCastOnGround:true
buildingDamageMultiplier:3

targetGround:true
[movement]
moveSpeed:0.72

[ai]
buildPriority:0.8

[hiddenAction_点数]
text:点数
autoTriggerOnEvent:destroyed
addResources:hero=1


[hiddenAction_initResTagCount]
autoTriggerOnEvent:created
setResourcesWithLogic:UnitPrice=600, UnitRadius=${core.radius}