[core]
name                       : 辐射
tags:Proxy
radius                     : 0
maxHp                      : 1
mass                       : 1
price                      : 100
fogOfWarSightRange         : 0
energyMax                  : 15
isUnrepairableUnit         : true
isUnselectable             : true
isUnselectableAsTarget     : true
canNotBeDirectlyAttacked   : true
canNotBeDamaged            : true
canNotBeGivenOrdersByPlayer: true
#showInEditor              : false
createNeutral              : true
createOnAggressiveTeam     : true


[turret_2]
x:0
y:0
energyUsage:1
aimOffsetSpread:0
projectile:2


[projectile_2]
life:100
areaDamage:30
areaRadius:175
flameWeapon:false
image:NONE.png
buildingDamageMultiplier:0
speed:1
explodeEffect:NONE
tags:辐射

[action_3]
autoTriggerOnEvent:completeAndActive
spawnEffects:NAME


[effect_NAME]
life:900
scaleTo:1.5
scaleFrom:1.5
fadeInTime:30
fadeOut:true
image:辐射.png
alpha:0.7
dirSpeed:0.2



[action_1]
text:att
autoTrigger:true
fireTurretXAtGround:2
fireTurretXAtGround_withOffset:0,0
addResources:energy=-1

[attack]
canAttack:false

[graphics]
image:NONE.png

[movement]
movementType:LAND

[action_2]
autoTrigger:if self.energy(lessThan=1)
deleteSelf:true

[decal_grade]
isVisible:false
