[core]
copyFrom            : ROOT:地球联合政府/坦克/装甲单位模板.ini,ROOT:unit-behaviors.template
name                : 辐射卡车
displayText         : 辐射卡车
displayDescription  : [装甲][自杀攻击]\n-可以给对方一点小小的辐射震撼\n-爆炸伤害不高, 但可以产生长时间的辐射尘
displayDescription_ja = [アーマー] [自殺攻撃] \ n-can相手に少し放射線ショックを与える\ n-抽出損傷は高くありませんが、長期の放射線ダストを生成する可能性があります
mass                : 1000
price               : 1000
maxHp               : 2000
radius              : 20
buildSpeed          : 30s
dieOnConstruct      : true
nanoRange           : 20
isBuilder           : true
transportSlotsNeeded: 4


[graphics]
image           : 辐射卡车.png
scaleImagesTo   : 50
turretImageScale: 1.5
dustEffect      : true
image_shadow:SHADOW:辐射卡车.png


[attack]
canAttack               : true
canAttackFlyingUnits    : false
canAttackLandUnits      : true
canAttackUnderwaterUnits: false
maxAttackRange          : 10
#isMelee                 : true
#meleeEngangementDistance: 250
dieOnAttack             : true
disablePassiveTargeting : true


[hiddenAction_die]
autoTriggerOnEvent            : destroyed
requireConditional            : if not self.hasFlag(id=5)
fireTurretXAtGround           : 1
fireTurretXAtGround_withOffset: 0, 0

[action_off]
isVisible   : if self.hasFlag(id=5)
addResources: unsetFlag=5
pos         : 1
text        : 取消保险
buildSpeed  : 0
iconImage   : error.png
description : 取消保险后 死亡将会爆炸

[action_on]
isVisible   : if not self.hasFlag(id=5)
addResources: setFlag=5
pos         : 1
text        : 启动保险
buildSpeed  : 0
iconImage   : correct.png
description : 启动保险后 死亡将不会爆炸

[turret_1]
x              : 0
y              : 0
aimOffsetSpread: 0


[projectile_1]
image         : NONE
areaDamage    : 300
areaRadius    : 175
life          : 1000
speed         : 1000
instant       : false
largeHitEffect: true

hitSound         : true
lightSize        : 300
lightColor       : #FF00FF00
lightCastOnGround: true
spawnUnit        : 辐射
buildingDamageMultiplier:0
friendlyFire:true


[effect_1]
life: 1000


[movement]
movementType          : LAND
moveSpeed             : 1
moveAccelerationSpeed : 0.1
moveDecelerationSpeed : 0.1
reverseSpeedPercentage: 0.4
maxTurnSpeed          : 4
turnAcceleration      : 1.2
moveSlidingMode       : 1


[action_boom]
autoTrigger : if self.teamId() == -2
buildSpeed  : 0
setUnitStats: hp=0
text        : 自爆!
addResources: unsetFlag=5
