[core]
name:倒计时
tags:Proxy
maxHp: 600
selfRegenRate:-0.5
radius:             1
price:              1
mass:               1
buildSpeed:         0
stayNeutral:        false
createOnAggressiveTeam:         true
showOnMinimap:      false
isUnselectable:     true
disableAllUnitCollisions:       true
isUnselectableAsTarget:         true
canNotBeDirectlyAttacked:       true
canNotBeDamaged:                true
canNotBeGivenOrdersByPlayer:    true
unitsSpawnedOnDeath:重点突破,烟幕倒计时
showInEditor:false

[hiddenAction_封烟]
autoTriggerOnEvent:created
spawnUnits:flare_10s
[decal_grade]
isVisible:false

[attack]
canAttack:          false
maxAttackRange:     1145141919


[graphics]
image:              NONE.png


[movement]
movementType:       NONE


#===================================================
