[core]
name:152
tags:Proxy
maxHp:   114514
radius:   1
price:    1
mass:     1
buildSpeed:         0
stayNeutral:        false
createOnAggressiveTeam:      true
showOnMinimap:      false
isUnselectable:     true

disableAllUnitCollisions:       true
isUnselectableAsTarget:         true
canNotBeDirectlyAttacked:       true
canNotBeDamaged:                true
canNotBeGivenOrdersByPlayer:    true
autoTriggerCooldownTime:1.2s
showInEditor:false
[attack]
canAttack:          false
maxAttackRange:     1145141919
[decal_grade]
isVisible:false

[graphics]
image:              NONE.png


[movement]
movementType:       AIR
targetHeight:       350
moveSpeed:          1

[action_i]
autoTriggerOnEvent:created
addResources:  time=7


[action_ii]
text:die
autoTrigger:        if self.resource(type='time',equalTo=0)
deleteSelf:    true


[action_iii]
autoTrigger:true
fireTurretXAtGround:1
addResources:time=-1
fireTurretXAtGround_withOffset: -2000,-10000
[turret_1]
x:0
y:0
image:NONE.png



[projectile_1]
image:white_pixel.png
life:1000
areaDamage:40
areaRadius:80
drawSize:1.5

speed:12
targetSpeed:16
color:#FFFFFF

largeHitEffect:true
buildingDamageMultiplier:5

initialUnguidedSpeedHeight:4
gravity:1
speedSpread:4
targetGroundSpread:200
targetGround:true

spawnUnit:碎片效果器
explodeEffect:CUSTOM:lark
#,CUSTOM:liofog*2,CUSTOM:火光
#,CUSTOM:lcjb,custom:LDfog*2,custom:5*10,1
trailEffect:custom:weiyan
trailEffectRate:0.5


[effect_1]
alsoPlaySound:火炮落地c.wav


[effect_weiyan]
life:40
image:light_50.png
attachedToUnit:false
alpha:0.4
scaleFrom:0.4
scaleTo:0
fadeOut:true

[resource_time]
displayName:time
hidden:true

[effect_5]
life:80
color:#000000
image:white_pixel.png
xSpeedRelativeRandom:5
ySpeedRelativeRandom:5

physics:true

physicsGravity:0.1


[effect_liofog]
image:黑烟.png
drawUnderUnits:false

life:300
xOffsetRelative:0
yOffsetRelative:5
ySpeedRelative:0.15
xSpeedRelativeRandom:0.1
ySpeedRelativeRandom:0.1
atmospheric:true
xSpeedRelative:0
scaleFrom:1
priority: low
scaleTo:4
fadeOut:true
fadeInTime:50
dirOffsetRandom:180
alpha:0.35

[effect_LDfog]
image:黑烟.png
drawUnderUnits:false

life:300
xOffsetRelative:0
yOffsetRelative:0

scaleFrom:3
priority: low
scaleTo:4.5
fadeOut:true
dirOffsetRandom:180
alpha:0.45

atmospheric:true
[effect_火光]
spawnChance:1
stripIndex:light_50
color:#BAB925
drawUnderUnits:false
life:10
ySpeedRelative:0
xSpeedRelativeRandom:0
ySpeedRelativeRandom: 0
atmospheric:true
xSpeedRelative:0.5
scaleFrom:2
scaleTo:2
fadeOut:true
alpha:0.25
attachedToUnit:false
hSpeed:0
hOffset:0

[effect_lark]
image:坑.png

scaleFrom:1
scaleTo:1
fadeInTime:0
dirOffsetRandom:180
alpha:0.6
drawUnderUnits:true

life:500
xOffsetRelative:0
yOffsetRelative:0
fadeOut:true
attachedToUnit:false

[effect_lcjb]
priority:high
image:ripple.png
drawUnderUnits:false
life:30
color:#FFFFFF
xSpeedRelativeRandom:0
ySpeedRelativeRandom:0
atmospheric:true
scaleFrom:0.2
scaleTo:2.7
fadeOut:true
fadeInTime:20
alpha:0.75
attachedToUnit:False
dirOffsetRandom:120
