[core]
price: 10
maxHp: 100
mass: 9000
radius: 16
name: 烟幕
tags:Proxy
displayText: 烟幕
#isBuilding: true
isUnselectable:true
canNotBeDirectlyAttacked:true
canNotBeDamaged:true
disableAllUnitCollisions:true

autoTriggerCooldownTime:0.1s
[hiddenAction_Remove]
autoTrigger: if self.timeAlive(laterThanSeconds=20)
text: Remove
deleteSelf: true

[hiddenAction_BlackS]

autoTrigger:true

fireTurretXAtGround: 1
fireTurretXAtGround_withOffset: 0,0
[decal_grade]
isVisible:false
[graphics]
image:        SHARED:blank.png




[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

maxAttackRange: 100
[movement]
movementType: NONE


[turret_1]

invisible: true
x:0
y:0

projectile: 1
size: 0
turnSpeed: 99

[projectile_1]

targetGroundSpread:200
life: 99
instant:true

drawSize:0

explodeEffect:smoke
targetGround: true
areaDamage:0

hitSound:false
[effect_smoke]

image:glow_sharp.png
imageShadow:glow_sharp.png

life: 300
fadeOut: true
attachedToUnit: false

color: #A1A1A1

fadeInTime:36
scaleFrom: 7
scaleTo:12
alpha: 0.8

liveAfterAttachedDies: true

hSpeed:0.2
hSpeedRandom:0.4
dirOffsetRandom:180
atmospheric:true

xOffsetAbsoluteRandom:30
yOffsetAbsoluteRandom:30

xOffsetRelativeRandom:45
yOffsetRelativeRandom:45


