[core]
name:烟幕倒计时
tags:Proxy
maxHp: 460
selfRegenRate:-1
radius:             1
price:              1
mass:               1
buildSpeed:         0
stayNeutral:        false
createOnAggressiveTeam:         true
showOnMinimap:      false
isUnselectable:     true
disableAllUnitCollisions:       true
isUnselectableAsTarget:         true
canNotBeDirectlyAttacked:       true
canNotBeDamaged:                true
canNotBeGivenOrdersByPlayer:    true
showInEditor:false

unitsSpawnedOnDeath:烟幕

[attack]
canAttack:          false
maxAttackRange:     1
[decal_grade]
isVisible:false

[graphics]
image:              NONE.png

icon_zoomed_out_neverShow:true
showHealthBar:true
[movement]
movementType:       NONE


#===================================================
