[core]
name:生成点
tags:Proxy
maxHp:              60
selfRegenRate:-0.5
radius:             1
price:              1
mass:               1
buildSpeed:         0
stayNeutral:        false
createOnAggressiveTeam:         true
showOnMinimap:      false
isUnselectable:     true
disableAllUnitCollisions:       true
isUnselectableAsTarget:         true
canNotBeDirectlyAttacked:       true
canNotBeDamaged:                true
canNotBeGivenOrdersByPlayer:    true
hideScorchMark:false
explodeOnDeath:false
showInEditor:false
[attack]
canAttack:          false
maxAttackRange:     1145141919

[decal_grade]
isVisible:false
[graphics]
image:              NONE.png


[movement]
movementType:       NONE


#=====================================================================

[hiddenAction_出现]
autoTriggerOnEvent:created
spawnUnits:152*5(offsetRandomX=100,offsetRandomY=100,offsetHeight=600)
[turret_1]
x:0
y:0
image:NONE.png


[projectile_1]
life:10
image:NONE.png
directDamage:0


[resource_time]
displayName:time
hidden:true
