[core]
name:重点突破
maxHp: 60
selfRegenRate:-0.5
radius:             1
price:              1
mass:               1
buildSpeed:         0
stayNeutral:        false
createOnAggressiveTeam:         true
showOnMinimap:      false
isUnselectable:     true
disableAllUnitCollisions:       true
isUnselectableAsTarget:         true
canNotBeDirectlyAttacked:       true
canNotBeDamaged:                true
canNotBeGivenOrdersByPlayer:    true
tags:打击点,Proxy
showInEditor:false
[attack]
canAttack:          false
maxAttackRange:     1145141919


[graphics]
image:              NONE.png
[decal_grade]
isVisible:false

[movement]
movementType:       NONE


#=====================================================================

[hiddenAction_斜率]
autoTriggerOnEvent:created
spawnUnits:生成点(offsetX=10000,offsetY=2000,offsetRandomX=50,offsetRandomY=50)
#,flare_10s
[turret_1]
x:0
y:0
image:NONE.png


[projectile_1]
life:10
image:NONE.png
directDamage:0


[resource_time]
displayName:time
hidden:true
