[core]
copyFrom:ROOT:地球联合政府/坦克/装甲单位模板.ini,ROOT:unit-behaviors.template
name:玄武坦克展开
displayText:玄武坦克展开
displayDescription:[装甲][对地][反装甲/反步兵/反建筑]\n-收起时单发伤害高\n-展开后溅射范围大\n-展开时射程有点短......
displayDescription_ja = [アーマー] [配信] [反装甲/反輸送/反アーキテクチャ] \ nシングルダメージが片付けられたときに高い。
mass:3000
price:1500
maxHp:4500
radius:30
buildSpeed:60s
maxTransportingUnits:0
armour:20
transportSlotsNeeded:6
isBuilding:true
selfRegenRate:0.03
footprint:-1,-1,1,1

[graphics]
image:玄武坦克.png
scaleImagesTo:40
dustEffect:true
total_frames:2
turretImageScale:1.2
animation_moving_start:0
animation_moving_end:1
animation_moving_speed:5


[attack]
maxAttackRange:160
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
showRangeUIGuide:true

#[turret_1]
#image:坦克炮塔.png
#x:0
#y:0
#shoot_sound:missile_fire
#shoot_light:#FF000000
#recoilOffset:-3
#recoilOutTime:2
#recoilReturnTime:10
#delay:60
#
#[projectile_1]
#image:抛射体.png
#life:100
#speed:1
#directDamage:100
#color:#FFAAAAAA
#drawSize:0.5
#lightSize:1
#lightCastOnGround:true
#lightColor:#FFAA0000

[turret_2]
image:炮管.png
x:0
y:10
shoot_sound:missile_fire
shoot_light:#FF000000
recoilOffset:-2
recoilOutTime:2
recoilReturnTime:120
attachedTo:1
slave:1
delay:150

[turret_1]
image:坦克炮塔.png
x:0
y:0
shoot_sound:missile_fire
shoot_light:#FF000000
recoilOffset:-2
recoilOutTime:2
recoilReturnTime:120
delay:150
turnSpeed:1
projectile:2
[projectile_1]
image:抛射体1.png
life:100
areaDamage:150
areaRadius:45
areaDamageNoFalloff:true
color:#FFAAAAAA
drawSize:0.5
lightCastOnGround:true
speed:20
trailEffect:true
trailEffectRate:0.1
largeHitEffect:true
lightColor:#ffff00
lightSize:0.2
[projectile_2]
life:100
image:NONE
areaDamage:0
areaRadius:0
invisible:true
deflectionPower:-1

#[animation_1]
#onActions:move
[hiddenAction_AI攻击]
text:AI攻击
displayType:action
buildSpeed:1
pos:0.1
autoTrigger:if self.hp(greaterThan=1000) and self.isControlledByAI and self.resource(type="credits",greaterThan=10000)
addWaypoint_type:attackmove
addWaypoint_target_nearestUnit_team:enemy
addWaypoint_target_nearestUnit_tagged:lives,tank
[movement]
movementType:BUILDING
moveSpeed:0
[leg_1]
attach_x:0
attach_y:0
x:-14
y:-14
image_foot:玄武坦克支架.png
drawOverBody:false

[leg_2]
attach_x:0
attach_y:0
x:14
y:-14
image_foot:玄武坦克支架.png
drawOverBody:false

[leg_3]
attach_x:0
attach_y:0
x:-14
y:14
image_foot:玄武坦克支架.png
drawOverBody:false

[leg_4]
attach_x:0
attach_y:0
x:14
y:14
image_foot:玄武坦克支架.png
drawOverBody:false

[action_trans]
text:收起
buildSpeed:1s
convertTo:玄武坦克
