[core]
name : 燃料精炼站
price: 2000
copyFrom:ROOT:地球联合政府/建筑/建筑模板.ini,ROOT:unit-behaviors.template
mass:114514
radius:30
maxHp:3000
armour:2
displayDescription:[建筑][支援科技]\n-允许建造喷火步兵\n-步战和机枪塔获得喷火升级\n-获得支援技能 空投白磷弹 有效加强指定位置的喷火步兵\n-允许世纪轰炸机换装燃烧炸弹
displayDescription_ja = [アーキテクチャ] [サポートテクノロジー] \ n-fire噴射歩兵の建設\ nウォーキングとマシンガンタワーは、火災注入のアップグレードを得るためにサポートスキルを獲得し、航空投資ホワイトリン爆弾を効果的に強化します。燃える爆弾
isBuilding:true
footprint:-1,-1,1,1
constructionFootprint:-1,-1,1,1
#buildingToFootprintOffsetX:0
tags:燃料精炼站,Valid
energyMax:1
energyStartingPercentage:0
energyRegen:0.0002
buildSpeed:60s
buildingToFootprintOffsetY:0

[graphics]
image:喷火科技.png
scaleImagesTo:60


[attack]
canAttack:false
maxAttackRange:114514

[turret_1]
x:0
y:0
shoot_sound_vol:0
image:NONE
delay:0
projectile:1


[projectile_1]
life:1000
speed:10000
areaDamage:-100
areaRadius:65
friendlyFire:true
mutator1_ifUnitWithTags:lives
mutator1_addResourcesAreaHit:白磷=15
targetGround:true
deflectionPower:-1
instant:true


[action_1]
buildSpeed:0s
text:空投白磷弹
description:给喷火步兵空投更好的燃料 增加伤害和射速
fireTurretXAtGround:1
onlyOneUnitAtATime:true
price:energy=1

[movement]
movementType:BUILDING

[resource_白磷]
hidden:true

[ai]
buildPriority:0.1
noneInBaseExtraPriority:0.5
recommendedInEachBaseNum:2
recommendedInEachBasePriorityIfUnmet:0.35
maxEachBase:3
