#@global boolean: allGunShoot

[core]
copyFrom:ROOT:SPARK/SPARK.template,ROOT:unit-behaviors.template

name:SPARK T1指挥官
displayText:SPARK 指挥官
displayDescription:[对地][T1][陆地]\n必须保护的重要单位,本身具有较强的火力,并且具有较高的建造速度
price:5000
maxHp:10000
armour:5
mass:100000
radius:40
tags:SPARK,ACU,Valid
canRepairBuildings:true
canRepairUnits:true
autoRepair:true
nanoRange:140

nanoRepairSpeed:0.4
nanoBuildSpeed:2
defineUnitMemory:boolean allGunShoot,boolean allGun1Shoot,boolean allowHpAdd
borrowResourcesWhileAlive:maxFactories=-3
@memory factoryupgradetimes:number

fireTurretXAtSelfOnDeath:died


[canBuild_1]
pos:1
name:T1 SPARK机器人工厂

[canBuild_2]
pos:2
name:SPARK T1资源提取器

[canBuild_3]
pos:3
name:T1 SPARK空军工厂

[canBuild_4]
pos:4
name:SPARK T1防空防御塔
addResources:hp=-500

[canBuild_5]
pos:3
name:SPARK T1对地防御塔
addResources:hp=-500




[graphics]
image:SPARK指挥官.png
scaleImagesTo:80

image_shadow:SHADOW:SPARK指挥官.png
shadowOffsetX:2
shadowOffsetY:2
image_turret:SPARK指挥官炮台.png
scaleTurretImagesTo:80

repairEffectAtTarget:CUSTOM:repair
repairEffectRate:180
repairEffect:CUSTOM:repair2
lock_body_rotation_with_main_turret:true

[effect_repair]
life:360
showInFog:false
priority:high
attachedToUnit:true
#atmospheric:true
image:维修效果c.png
total_frames:6
animateFrameStart:0
animateFrameEnd:5
animateFrameSpeed:0.5
animateFrameSpeedRandom:0.2
animateFrameLooping:true
teamColorRatio:0.1

dirSpeed:1
dirSpeedRandom:0.3

[effect_repair2]
life:360
showInFog:false
priority:high
attachedToUnit:true
#atmospheric:true
image:圆圈.png
total_frames:1
scaleTo:3
scaleFrom:0.01
teamColorRatio:0.3
#shadow:true
hSpeed:0.01
fadeInTime:20
fadeOut:true
dirSpeed:100
alpha:0.6

[attack]
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
setMainTurretAs:main
maxAttackRange:320


[movement]
movementType:LAND
moveSpeed:0.4
moveAccelerationSpeed:0.05
moveDecelerationSpeed:0.05
targetHeight:1
targetHeightDrift:1
maxTurnSpeed:2
turnAcceleration:1.5
moveIgnoringBody:true

[global_resource_maxFactories]
displayName:产能

hidden:false

#==========================================


[hiddenAction_Initialize]
autoTriggerOnEvent:created
setUnitMemory:allGunShoot=false,allGun1Shoot=false,allowHpAdd=false,factoryupgradetimes=1

[action_upgrade_gun]
buildSpeed:30s
isVisible:if memory.allGunShoot==false
text:升级_获得火炮
description:获得一门远程火炮
price:12000
setUnitMemory:allGunShoot=true

[action_upgrade_gun1]
text:升级_获得机枪
buildSpeed:40s
isVisible:if memory.allGun1Shoot==false
attachments_addNewUnits:SPARK指挥官附属机枪
price:6000
attachments_onlyOnSlots:1
setUnitMemory:allGun1Shoot=true

[action_upgrade_autoRepair]
text:升级_获得自动修复
buildSpeed:20s
isVisible:if memory.allowHpAdd==false
price:4000
setUnitMemory:allowHpAdd=true

[action_upgrade_massadd]
text:质量生成($ %{memory.factoryupgradetimes*800})
buildSpeed:0s
description:消耗%{memory.factoryupgradetimes*memory.factoryupgradetimes*800}来制造1点产能
price:0
isLocked:if not (self.resource.credits >= memory.factoryupgradetimes*800)
#requireConditional:if (self.resource.credits >= memory.factoryupgradetimes*800)
addActionCooldownTime:20s

setUnitMemory:factoryupgradetimes=memory.factoryupgradetimes+1
addResourcesWithLogic:maxFactories=1,credits=-memory.factoryupgradetimes*800

[hiddenAction_allowHpAdd]
autoTrigger:if memory.allowHpAdd==true
addResources:hp=5


#==========================================

[turret_died]
image:ROOT:shared/NONE.png
x:0
y:0
canShoot:false
[projectile_died]
areaDamage:6000
areaRadius:300
areaHitAirAndLandAtSameTime:true
largeHitEffect:true

life:30




[turret_gun]
onShoot_freezeBodyMovementFor:0.2s
x:0
y:38
image:SPARK指挥官炮管.png
attachedTo:main
slave:true

recoilOffset:-10
recoilOutTime:6
recoilReturnTime:60
delay:180
barrelY:20

turnSpeed:0.3
turnSpeedAcceleration:0.1
turnSpeedDeceleration:0.1
shoot_sound:cannon_firing

canAttackLandUnits:if self.readUnitMemory('allGunShoot',type='boolean') == true
invisible:if self.readUnitMemory('allGunShoot',type='boolean') == false
projectile:gun
[projectile_gun]
life:320
areaDamage:360
areaRadius:30
speed:3
frame:2
explodeEffect:shockwave

[turret_main]
onShoot_freezeBodyMovementFor:0.2s
x:0
y:0
turnSpeed:0.3
turnSpeedAcceleration:0.1
turnSpeedDeceleration:0.1

canShoot:false


[attachment_1]
x:0
y:0
#onCreateSpawnUnitOf:SPARK指挥官附属机枪
isUnselectable:true

[ai]
useAsBuilder:true
