
[core]
copyFrom:ROOT:SPARK/SPARK.template,ROOT:templete/SPARK_factory.ini,ROOT:unit-behaviors.template

nanoFactorySpeed:2
showActionsWithMixedSelectionIfOtherUnitsHaveTag:bulitaryBuilding

name:T2 SPARK战车工厂
displayText:T2 SPARK战车工厂
displayDescription:[工厂][无法攻击][T2][建筑]\n用于生产更高级战车单位的工厂\n拥有简易护甲\n-在未达到工厂数量上限时,可消耗「馈赠」提升生产速度
buildSpeed:360s
price:0
borrowResourcesWhileBuilt:maxFactories=2
radius:30
tags:produceBuildings,bulitaryBuilding,Valid
mass:10000
isBuilding:true
maxHp:2500
armour:5
footprint:-1,-1,2,2
constructionFootprint:-2,-2,3,4
buildingToFootprintOffsetX:20
canBuild_1_name:setRally
canBuild_1_pos:0
maxTransportingUnits:4
transportUnitsRequireTag:technology
transportUnitsBlockOtherTransports:false
transportUnitsBlockAirAndWaterUnits:false
transportUnitsRequireMovementType:HOVER
defineUnitMemory:float nanoBuildSpeedMemory
#[hiddenAction_addTechGrade]
#autoTrigger:if self.resource.Gift>2000

@memory resourceBuilding:unit[]     
[graphics]
image:SPARK T2战车工厂.png
scaleImagesTo:110
image_back:SPARK 战车工厂背景.png


[canBuild_2]
pos:1
name:SPARK T1 建造者

[canBuild_3]
pos:2
name:SPARK 跳蛛机甲


[ai]
buildPriority:0.8
noneInBaseExtraPriority:1
noneGlobalExtraPriority:1
recommendedInEachBaseNum:20
maxGlobal:100

[hiddenAction_initBuildSpeed]
autoTriggerOnEvent:created
setUnitMemory:nanoBuildSpeedMemory=2





[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=3000

[action_stop]
text:工厂维护
pos:0.1
isVisible:if not self.hasFlag(id=31)
description:暂时停止工厂以使其余工厂恢复生产
addResources:setFlag=31,maxFactories=1
buildSpeed:0s
setUnitStats:nanoFactorySpeed=0.01
highPriorityQueue:true
onlyOneUnitAtATime:true
displayType:action
iconImage:ROOT:/shared/错误.png

[action_unstop]
text:工厂开工
pos:0.1
isVisible:if self.hasFlag(id=31)
description:启动工厂工厂以恢复生产
addResources:unsetFlag=31,maxFactories=-1
setUnitStats:nanoFactorySpeed=0.2
buildSpeed:0s
highPriorityQueue:true
displayType:action


[hiddenAction_massEffect]
autoTrigger:if self.resource.Gift>100
spawnEffects:CUSTOM:massGiven

#[hiddenAction_addnanoByGift]
#autoTrigger:if self.hp()==self.maxHp() and self.resource.Gift>100
#setUnitStats:nanoFactorySpeed+=0.1
#addResources:Gift=-100
