
[core]
copyFrom:ROOT:SPARK/SPARK.template,ROOT:templete/SPARK_factory.ini,ROOT:unit-behaviors.template

nanoFactorySpeed:1.5
showActionsWithMixedSelectionIfOtherUnitsHaveTag:FlyingBuilding

name:T1 SPARK空军工厂
displayText:T1 SPARK空军工厂
displayDescription:[工厂][无法攻击][T1][建筑]\n用于生产空中飞行单位的简易工厂\n拥有简易护甲\n-在未达到工厂数量上限时,可消耗「馈赠」提升生产速度
buildSpeed:40s
price:0
borrowResourcesWhileBuilt:maxFactories=2

radius:30
tags:produceBuildings,Valid
mass:10000
isBuilding:true
maxHp:3500
armour:5
footprint:0,0,1,1
constructionFootprint:-1,-1,2,2
buildingToFootprintOffsetX:20
canBuild_1_name:setRally
canBuild_1_pos:0
maxTransportingUnits:4
transportUnitsRequireTag:technology
transportUnitsBlockOtherTransports:false
transportUnitsBlockAirAndWaterUnits:false
transportUnitsRequireMovementType:HOVER

defineUnitMemory:float nanoBuildSpeedMemory


#[hiddenAction_addTechGrade]
#autoTrigger:if self.resource.Gift>1000
#
#
##convertTo:T2 SPARK机器人工厂
#addResources:Gift=-1000
#
#[hiddenAction_addTechGrade1]
#autoTrigger:if self.transportingCount(greaterThan=3)
#deleteNumUnitsFromTransport:4
#
##convertTo:T2 SPARK机器人工厂

[graphics]
image:空军基地.png
scaleImagesTo:70
image_back:空军基地背景.png



[arm_1]
x:0
y:0
image_end:空军基地盖子.png
#draw_foot_on_top:true
#drawOverBody:true

[animation_1]
onActions:queuedUnits
blendIn:5s
blendOut:2s
arm1_0:{y:-14}

[canBuild_1]
pos:1
name:SPARK T1飞行机器人

[canBuild_2]
pos:2
name:SPARK哈迪斯拦截机

[canBuild_3]
pos:3
name:武装直升机


[ai]
buildPriority:0.8
noneInBaseExtraPriority:1
noneGlobalExtraPriority:1
recommendedInEachBaseNum:20
maxGlobal:100

[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=2000



[action_stop]
text:工厂维护
pos:0.1
isVisible:if not self.hasFlag(id=31)
description:暂时停止工厂以使其余工厂恢复生产
addResources:setFlag=31,maxFactories=2
buildSpeed:0s
setUnitStats:nanoFactorySpeed=0.01
highPriorityQueue:true
onlyOneUnitAtATime:true
displayType:action
iconImage:ROOT:/shared/错误.png

[action_unstop]
text:工厂开工
pos:0.1
isVisible:if self.hasFlag(id=31)
description:启动工厂工厂以恢复生产
addResources:unsetFlag=31,maxFactories=-2
setUnitStats:nanoFactorySpeed=0.2
buildSpeed:0s
highPriorityQueue:true
displayType:action


[hiddenAction_massEffect]
autoTrigger:if self.resource.Gift>100
spawnEffects:CUSTOM:massGiven

#[hiddenAction_addnanoByGift]
#autoTrigger:if self.hp()==self.maxHp() and self.resource.Gift>100
#setUnitStats:nanoFactorySpeed+=0.1
#addResources:Gift=-100



