[core]
name:空军效果单位_产生移动炮台车
displayDescription:你不应该看见他
displayDescription_ja = あなたは彼を見るべきではありません

price:500
mass:1000
buildSpeed:20s
maxHp:240
radius:15
energyStartingPercentage:1
energyMax:3
disableAllUnitCollisions:true
tags:plane,Proxy
fireTurretXAtSelfOnDeath:1
isUnselectable:true


#defineUnitMemory:



[graphics]
image:攻击机.png
scaleImagesTo:30
image_shadow:AUTO
drawLayer:top

[attack]
maxAttackRange:40
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
disablePassiveTargeting:true



[movement]
movementType:AIR
moveSpeed:2.5
moveAccelerationSpeed:0.5
moveDecelerationSpeed:0
landOnGround:false
targetHeight:50
maxTurnSpeed:3
turnAcceleration:1
moveSlidingMode:true
slowDeathFall:true
joinsGroupFormations:false
reverseSpeedPercentage:0


[projectile_1]
teleportSource:true
invisible:true
speed:114514
life:1000
directDamage:0




[action_be_act_for_the_first]
autoTriggerOnEvent:created



[action_sub_life]
autoTrigger:true
addResources:time=1


[action_dead]
autoTrigger:if self.resource(type='time',greaterThan=4)
setUnitStats:hp=0



[resource_time]
displayName:time
displayRoundedDown:true

[resource_speed]
hidden:false
