[core]
name:SPARK哈迪斯拦截机
displayText:哈迪斯拦截机

copyFrom:ROOT:SPARK/SPARK.template,ROOT:unit-behaviors.template
displayDescription:[固定翼飞机][拦截机][对空]\n-不错的制空单位

price:0
mass:1000
buildSpeed:55s
maxHp:250
radius:10

disableAllUnitCollisions:false
tags:planes,Valid


[graphics]
image:战斗机.png
scaleImagesTo:30
image_shadow:AUTO
drawLayer:top

[attack]
maxAttackRange:120
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
disablePassiveTargeting:false
isFixedFiring:false

[turret_1]
x:0
y:0
delay:80
canAttackCondition:if not self.isAtGroundHeight
turnSpeed:100
shoot_sound:plasma_fire
canOnlyAttackUnitsWithTags:planes

#limitingAngle:30

[projectile_1]
life:100
speed:20
directDamage:150
[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=600

[movement]
movementType:AIR
moveSpeed:2
moveAccelerationSpeed:0.01
moveDecelerationSpeed:0.01
landOnGround:true
targetHeight:50
maxTurnSpeed:6
turnAcceleration:0.2
moveSlidingMode:false
slowDeathFall:true
joinsGroupFormations:false
reverseSpeedPercentage:0
heightChangeRate:0.1
