[core]
name:SPARK 无人拦截机
copyFrom:ROOT:SPARK/SPARK.template,ROOT:unit-behaviors.template
displayText:SPARK 无人拦截机
displayDescription:SPARK无人巢中起飞的无人机,拥有高的对空效率
isUnselectableAsTarget:true
maxHp:100
radius:1
price:0
mass:100
tags:noHumanPlane,Valid
@memory selfparent:unit
@memory ableToLive:boolean

[graphics]
image:拦截机.png

[movement]
movementType:AIR
moveSpeed:2
moveAccelerationSpeed:0.08
moveDecelerationSpeed:0.01
landOnGround:false
targetHeight:15
maxTurnSpeed:3
turnAcceleration:0.2
moveSlidingMode:true
slowDeathFall:true
joinsGroupFormations:true
reverseSpeedPercentage:0
targetHeightDrift:5
moveIgnoringBody:false
heightChangeRate:0.05
fallingAcceleration:0.001

[attack]
canAttack:true
maxAttackRange:40
canAttackLandUnits:false
canAttackFlyingUnits:true
canAttackUnderwaterUnits:false

[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=100

[hiddenAction_initself]
autoTriggerOnEvent:created
setUnitMemory:selfparent=self.parent

[hiddenAction_attack]
autoTrigger:if not self.hasParent() and memory.selfparent.isAttacking()
clearAllWaypoints:true
addWaypoint_type:attackMove
addWaypoint_target_fromReference:memory.selfparent.attacking

[hiddenAction_back]
autoTrigger:if (not self.hasParent() and memory.selfparent.isAttacking()==false) or memory.selfparent==null or self.hasActiveWaypoint()==false

clearAllWaypoints:true
addWaypoint_type:loadInto
addWaypoint_target_fromReference:memory.selfparent
addWaypoint_triggerActionIfFailed:selfdead

[hiddenAction_initself2]
autoTriggerOnEvent:newMessage
setUnitStats:hp=0,maxHp=0

[hiddenAction_selfdead]
autoTrigger:if memory.selfparent==null
#autoTrigger:true
setUnitStats:hp=0,maxHp=0





[turret_1]
x:0
y:0
delay:120
canAttackCondition:if not self.isAtGroundHeight
turnSpeed:100
shoot_sound:plasma_fire
canAttackFlyingUnits:true
canAttackLandUnits:false
canAttackUnderwaterUnits:false


[projectile_1]
life:100
speed:20
directDamage:100
