[core]
copyFrom:ROOT:SPARK/SPARK.template,ROOT:unit-behaviors.template
name:SPARK 无人机控制站
tags:Valid
displayText:SPARK 无人机控制站
displayDescription:SPARK的无人机控制站,可以起飞各种先进飞行器
maxHp:500
armour:1
buildSpeed:120s
price:0
isBuilding:true
mass:114514
radius:30
footprint:-1,0,1,1
constructionFootprint:-1,0,1,1


maxTransportingUnits:6
transportUnitsBlockAirAndWaterUnits:false
transportUnitsRequireMovementType:AIR
transportUnitsHealBy:10
transportUnitsEachUnitAlwaysUsesSingleSlot:true
transportUnitsAddUnloadOption:false

@memory myplane:unit[]
@memory ableToLive:boolean

[action_change]
text:对地
description:改为制造攻击机
convertTo:SPARK 无人机控制站LAND
deleteNumUnitsFromTransport:6
buildSpeed:0


[hiddenAction_addPlane]
autoTrigger:if (memory.myplane.size<6 and self.numberOfAttachedUnits(lessThan=7) and self.resource.time%3==0) and self.resource.maxFactories>=0
addUnitsIntoTransport:SPARK 无人拦截机

[hiddenAction_content]
autoTrigger:true
takeResources_searchOnly:true
takeResources_includeUnitsWithinRange_team:own
takeResources_includeUnitsWithinRange:1
takeResources_maxUnits:1000
takeResources_triggerActionForEach:add
takeResources_excludeUnitsWithoutTags:noHumanPlane
takeResources_includeUnitsInTransport:true
shrinkArrays:myplane

[hiddenAction_add]
#setUnitMemory:resourceBuilding[]=[]
shrinkArrays:myplane
requireConditional:if not memory.myplane.contains(thisActionTarget)
setUnitMemory:myplane[memory.myplane.size]=thisActionTarget

[hiddenAction_planeGo]
autoTrigger:if self.isAttacking()
startUnloadingTransport:true

[hiddenAction_deaded0]
autoTriggerOnEvent:destroyed
sendMessageTo:memory.myplane[0]
sendMessageWithData:ableToLive=true

[hiddenAction_deaded1]
autoTriggerOnEvent:destroyed
sendMessageTo:memory.myplane[1]
sendMessageWithData:ableToLive=true

[hiddenAction_deaded2]
autoTriggerOnEvent:destroyed
sendMessageTo:memory.myplane[2]
sendMessageWithData:ableToLive=true

[hiddenAction_deaded3]
autoTriggerOnEvent:destroyed
sendMessageTo:memory.myplane[3]
sendMessageWithData:ableToLive=true

[hiddenAction_deaded4]
autoTriggerOnEvent:destroyed
sendMessageTo:memory.myplane[4]
sendMessageWithData:ableToLive=true

[hiddenAction_deaded5]
autoTriggerOnEvent:destroyed
sendMessageTo:memory.myplane[5]
sendMessageWithData:ableToLive=true

[decal_error]
image:ROOT:/shared/错误.png
layer:onTop
onlyWhileAlive:true
isVisible:if self.resource.maxFactories<0


[graphics]
image:无人机控制站.png
scaleImagesTo:64

[attack]
canAttack:true
canAttackLandUnits:false
canAttackFlyingUnits:true
canAttackUnderwaterUnits:false

maxAttackRange:600

[movement]
movementType:BUILDING

[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=800

[global_resource_maxFactories]
hidden:false
