[core]
name              : 大型地堡
displayDescription: [建筑][可驻军]\n-厚重的混凝土可以有效地保护其内部的士兵
displayDescription_ja = [建築] [駐rison地になることができます] \ n-厚さのコンクリートは、彼らの内部兵士を効果的に保護することができます
copyFrom:ROOT:地球联合政府/建筑/建筑模板.ini,ROOT:unit-behaviors.template
maxHp:1400
mass:114514
price:800
radius:20
buildSpeed:15s
#此模板在"基础模板"上修改
isBuilding:true
#此代码规定建筑范围
footprint:-1,-1,1,1
constructionFootprint:-1,-1,1,1
maxTransportingUnits:5


armour:10

[graphics]
#图像节需要设置主体图像
image:大型地堡.png
scaleImagesTo:60


[attack]
canAttack:true
canAttackLandUnits:true
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
turretRotateWithBody:false
turretTurnSpeed:3
attackMovement:normal
maxAttackRange:180
shootDelay:2
isFixedFiring:false

[attachment_1]
x=5
y=5
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true

[attachment_2]
x=-5
y=5
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true

[attachment_3]
x=5
y=-5
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true

[attachment_4]
x=-5
y=-5
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true

[attachment_5]
x=0
y=0
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true


[movement]
movementType:BUILDING
