[core]
name:引导目标
maxHp: 60

radius:             1
price:              1
mass:               1
buildSpeed:         0
stayNeutral:        true
#createOnAggressiveTeam:         true
showOnMinimap:      false
isUnselectable:     true
disableAllUnitCollisions:       true
isUnselectableAsTarget:         true
canNotBeDirectlyAttacked:       false
canNotBeDamaged:                true
canNotBeGivenOrdersByPlayer:    true
tags:引导目标,Proxy
energyMax:5
energyRegen:-0.005
canOnlyBeAttackedByUnitsWithTags:重型榴弹炮
showInEditor:false


[hiddenAction_1]
autoTrigger:if self.energy(empty=true)
deleteSelf:true

[hiddenAction_2]
autoTrigger:if self.energy<4.5
switchToAggressiveTeam:true




[attack]
canAttack:          false
maxAttackRange:     1145141919


[graphics]
image:              NONE.png


[movement]
movementType:       NONE
