[core]
name    : 重型榴弹炮
copyFrom:ROOT:地球联合政府/建筑/建筑模板.ini,ROOT:unit-behaviors.template
displayText:重型榴弹炮
displayDescription:[建筑][对地][反建筑]\n-最重型的火炮,对指定位置造成毁灭性的打击\n-在引导炮击冷却达到60后可释放一个引导炮击信标 随后所有己方重型榴弹炮都会攻击\n-限造4个
displayDescription_ja = [建築] [地球] [反アーキテクチャ] \ n-最も重い砲兵、指定された位置への壊滅的な打撃\ n- 60年代のガイダンスのガイダンスのガイダンスのガイダンスのガイダンスのガイダンスのガイダンスのガイダンスのガイダンスは、ガイダンスキャノンラベル攻撃をリリースすることができます\ n-limited 4
mass:114514
price:4000
maxHp:3500
radius:40
transportSlotsNeeded:100
buildSpeed:15s
isBuilding:true
footprint:-1,-1,1,1
constructionFootprint:-1,-1,1,1
energyMax:5
energyRegen:0.002
defineUnitMemory:unit target
tags:重型榴弹炮,Valid


[graphics]
image:榴弹炮底座.png
scaleImagesTo:60
turretImageScale:1.5
dustEffect:true



[attack]
maxAttackRange:800
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
showRangeUIGuide:true
canOnlyAttackUnitsWithTags:引导目标
disablePassiveTargeting:true


[action_1]
price:energy=5,引导炮击冷却=60
text:引导炮击
fireTurretXAtGround:3
#whenBuilding_rotateTo_rotateTurretX:1
#
#whenBuilding_rotateTo_aimAtActionTarget:true
#
#whenBuilding_cannotMove:true
#whenBuilding_rotateTo_waitTillRotated:true
#whenBuilding_rotateTo_rotateTurretX:1

[hiddenAction_引导目标]
autoTrigger:if memory.target    !=  nullUnit

#if distanceBetween(self, nearestUnit(withinRange=${attack.maxAttackRange},withTag='引导目标',relation='own'))<${attack.maxAttackRange}


#fireTurretXAtGround_withTarget:memory.target
#fireTurretXAtGround:1
#whenBuilding_rotateTo_rotateTurretX:1
#whenBuilding_rotateTo_aimAtActionTarget:true
#whenBuilding_cannotMove:true
#whenBuilding_rotateTo_waitTillRotated:true

clearAllWaypoints:true
addWaypoint_type:attack
addWaypoint_target_fromReference:memory.target


[hiddenAction_i]
autoTrigger:if numberOfUnitsInTeam(greaterThan=0,withTag='引导目标')
setUnitMemory:target=nearestUnit(withinRange=${attack.maxAttackRange},withTag='引导目标',relation='own')


[hiddenAction_ii]
autoTrigger:if not numberOfUnitsInTeam(greaterThan=0,withTag='引导目标')
setUnitMemory:target=nullUnit

[turret_3]
x:0
y:0
projectile:3
canShoot:false


[turret_1]
image:榴弹炮炮塔c.png
x:0
y:5
barrelY:40
shoot_sound:missile_fire
shoot_light:#FF000000
recoilOffset:-10
recoilOutTime:2
recoilReturnTime:120
delay:300
turnSpeed:1
#projectile:2
limitingMinRange:120

[projectile_1]
image:抛射体3.png
life:1009
areaDamage:400
areaRadius:80
areaDamageNoFalloff:true
speed:6
color:#bebe50
drawSize:0.7
lightSize:0.3
lightCastOnGround:true
largeHitEffect:true
lightColor:#ffe92b
initialUnguidedSpeedHeight:1.2
gravity:0.2
targetGround:true
targetGroundSpread:50




[resource_teamid]
hidden:true

[projectile_3]
life:100
image:NONE.png
instant:true
directDamage:0
spawnUnit:引导目标

#[projectile_2]
#life:100
#image:NONE
#areaDamage:0
#areaRadius:0
#invisible:true
#deflectionPower:-1

[movement]
movementType:BUILDING


[placementRule_maxct]
maxCount:4
searchTags:重型榴弹炮
cannotPlaceMessage:请减小部署密度以降低后勤压力!
searchTeam:own
searchDistance:114514

[global_resource_引导炮击冷却]
displayName:引导炮击技能冷却
displayRoundedDown:true
