[core]
name:油桶
tags:Proxy
displayDescription:卖油!\n回收它,提供资金收入
displayDescription_ja = 石油の販売！\ nはそれを回収し、資本収入を提供します
price:          4000
radius:         10
maxHp:          1500
mass:           1145141919
#================================

armour:         1
#isBuilding:     false
resourceRate:   0.05
isBuilding:true


#================================

stayNeutral:    true
createNeutral:  false


#================================

[graphics]
image:          矿石资源.png
scaleImagesTo:  30

#================================

[attack]
canAttack:      false

#================================

[movement]
movementType:   LAND

#================================

[hiddenAction_deleteItSelf]
autoTrigger:if not self.isInMap
deleteSelf:true
