[core]
name:散射电流
tags:Proxy
maxHp:1
radius:1
price:1
fogOfWarSightRange:0
isUnselectableAsTarget:true
mass:1
isUnselectable:true
showInEditor:false

[graphics]
#图像节需要设置主体图像
image:空.png
scaleImagesTo:0
image_turret:NONE

[decal_grade]
isVisible:false
[attack]
canAttack:true
canAttackLandUnits:true
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
turretRotateWithBody:false
turretTurnSpeed:114514
attackMovement:normal
maxAttackRange:175
shootDelay:1
isFixedFiring:false
removeOnAttack:true
turretMultiTargeting:true


[turret_1]

limitingMinRange:1

shouldResetTurret:true

#复制自_1
canAttack:true
canAttackLandUnits:true
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
x:0
y:20
idleDir:0
shoot_sound:lighting_burst
clearTurretTargetAfterFiring:true


[projectile_1]
image:NONE
tags:flash
shouldRevealFog:true
lightingEffect:true

directDamage:10
life:10
speed:13
trailEffect:false
lightColor:#FFFFFF
mutatorX_ifUnitWithTags:tank
mutatorX_directDamageMultiplier:5
mutatorX_addResourcesDirectHit:stop=1
instantReuseLast:true
instant:true


[turret_2]

limitingMinRange:20

shouldResetTurret:true

#复制自_1
canAttack:true
canAttackLandUnits:true
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
x:0
y:20
idleDir:0
shoot_sound:lighting_burst
clearTurretTargetAfterFiring:true


[projectile_2]
image:NONE
tags:flash
shouldRevealFog:true
lightingEffect:true

directDamage:10
life:10
speed:13
trailEffect:false
lightColor:#FFFFFF
mutatorX_ifUnitWithTags:tank
mutatorX_directDamageMultiplier:5
mutatorX_addResourcesDirectHit:stop=1
instantReuseLast:true
instant:true

[turret_3]

limitingMinRange:1

shouldResetTurret:true

#复制自_1
canAttack:true
canAttackLandUnits:true
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
x:0
y:20
idleDir:0
shoot_sound:lighting_burst
clearTurretTargetAfterFiring:true


[projectile_3]
image:NONE
tags:flash
shouldRevealFog:true
lightingEffect:true

directDamage:10
life:10
speed:13
trailEffect:false
lightColor:#FFFFFF
mutatorX_ifUnitWithTags:tank
mutatorX_directDamageMultiplier:5
mutatorX_addResourcesDirectHit:stop=1
instantReuseLast:true
instant:true


[resource_stop]
hidden:true

[movement]
movementType:BUILDING
