[core]

name: 特斯拉电塔_散射升级
copyFrom:ROOT:地球联合政府/建筑/建筑模板.ini
maxHp:1100
mass:114514
price:1500
radius:13
buildSpeed:15s
#此模板在"基础模板"上修改
isBuilding:true
#此代码规定建筑范围
footprint:-1,0,1,1
constructionFootprint:-1,0,1,1

armour:3

[graphics]
#图像节需要设置主体图像
image:特斯拉电塔s.png
image_turret:NONE
scaleImagesTo:50

[attack]
canAttack:true
canAttackLandUnits:true
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
turretRotateWithBody:false
turretTurnSpeed:114514
attackMovement:normal
maxAttackRange:245
shootDelay:1
isFixedFiring:false



[turret_1]


shouldResetTurret:true

#复制自_1
canAttack:true
canAttackLandUnits:true
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
x:0
y:20
idleDir:0
shoot_sound:电流响声.wav
clearTurretTargetAfterFiring:true


[projectile_1]
image:NONE
tags:flash
shouldRevealFog:true
lightingEffect:true
spawnUnit:散射电流

directDamage:10
life:10
speed:13
trailEffect:false
lightColor:#FFFFFF
mutatorX_ifUnitWithTags:tank
mutatorX_directDamageMultiplier:5
mutatorX_addResourcesDirectHit:stop=1
instantReuseLast:true
instant:true

[turret_2]


shouldResetTurret:true

#复制自_1
canAttack:false
canAttackLandUnits:true
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
x:0
y:20
idleDir:0
shoot_sound:电流响声.wav
clearTurretTargetAfterFiring:true
projectile:2

[projectile_2]
image:NONE
tags:flash
shouldRevealFog:true
lightingEffect:true
explodeEffect:NONE


directDamage:10
life:10
speed:13
trailEffect:false
lightColor:#FFFFFF
mutatorX_ifUnitWithTags:tank
mutatorX_directDamageMultiplier:5
mutatorX_addResourcesDirectHit:stop=1
instantReuseLast:true
instant:true


[hiddenAction_attackItSelf]
autoTrigger:true
fireTurretXAtGround:2
fireTurretXAtGround_withOffset:0,-10


[movement]
movementType:BUILDING

[resource_stop]
hidden:true
