[core]

name: SPARK T1防御碉堡
tags:Valid
copyFrom:ROOT:SPARK/SPARK.template,ROOT:unit-behaviors.template
displayDescription:[建筑][可驻军]\n-由建造者建造的小型地堡\n-拥有很不错的火力,同时可以灵活执行任务
maxHp:3600
mass:114514
price:0
radius:20

isBuilding:true
footprint:-1,-1,1,1
constructionFootprint:-1,-1,1,1
maxTransportingUnits:6
buildSpeed:60s
selfBuildRate:60s
transportUnitsRequireTag:T1

armour:1

[graphics]
#图像节需要设置主体图像
image:碉堡.png
scaleImagesTo:80
image_shadow:SHADOW:碉堡.png
shadowOffsetX:2 
shadowOffsetY:2 


[attack]
canAttack:true
canAttackLandUnits:true
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
turretRotateWithBody:false
turretTurnSpeed:30
attackMovement:normal
maxAttackRange:140
shootDelay:2
isFixedFiring:false

[attachment_1]
x=-10
y=10
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true

[attachment_2]
x=-10
y=0
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true


[attachment_3]
x=-10
y=-10
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true

[attachment_4]
x=10
y=10
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true

[attachment_5]
x=10
y=0
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true

[attachment_6]
x=10
y=-10
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true

[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=1000



[movement]
movementType:BUILDING
