[core]
copyFrom:ROOT:SPARK/SPARK.template,ROOT:unit-behaviors.template


name:SPARK T1战斗机器人

displayText:T1战斗机器人
displayDescription:[对地][T1][陆地]\n前期的廉价机器人\n火力较为贫乏,对建筑伤害较低
price:0
mass:2000
maxHp:300
tags:Tech1GunRobot,T1,Valid
radius:7
buildSpeed:20s

[graphics]
#image:SPARK T1战斗机器人c.png
image:SPARK T1战斗机器人主体.png
scaleImagesTo:20
image_shadow:SHADOW:SPARK T1战斗机器人c.png
image_wreak:SPARK T1战斗机器人残骸.png

shadowOffsetX:1
shadowOffsetY:1
teamColorsOnTurret:true

image_turret:SPARK T1战斗机器人c.png
scaleTurretImagesTo:20
lock_body_rotation_with_main_turret:true

[attack]
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:80


[turret_1]
x:0
y:0

shoot_sound:gun_fire

recoilOffset:-2
recoilOutTime:4
recoilReturnTime:30



idleSweepSpeed:0.3
idleSweepAngle:60
idleSweepDelay:180
idleSweepAddRandomDelay:100
idleSweepAddRandomAngle:20
idleSweepCondition:if not self.isMoving()
delay:80



barrelX:5
barrelY:5

[projectile_1]
directDamage:80
life:100
frame:1
drawSize:0.7
speed:5
lightSize:0.8
lightColor:#FF882200
buildingDamageMultiplier:0.4

[movement]
movementType:LAND
moveSpeed:0.5

moveAccelerationSpeed:0.1
moveDecelerationSpeed:0.1

maxTurnSpeed:5
turnAcceleration:8
moveIgnoringBody:true
reverseSpeedPercentage:0


[leg_1]
x: -4
y: 4
endDirOffset:225
attach_x:-0
attach_y:0
moveSpeed: 2
resetAngle:225
dust_effect:false
image_leg:  足c.png

holdDisMin:0.5
holdDisMax:2
hardLimit:5
holdDisMin_checkNeighbours:true
favourOppositeSideNeighbours:true
estimatingPositionMultiplier:0.2

#image_foot: foot1.png

[leg_2]
copyFrom:1
attach_x:0
attach_y:0
x:4
y:4
image_leg:足c.png
#dust_effect:true
[leg_3]
copyFrom:1
attach_x:-0
attach_y:-0
x:-4
y:-4
#dust_effect:true
image_leg:足c.png
[leg_4]
attach_x:0
attach_y:-0
copyFrom:1
x:4
y:-4
image_leg:足c.png

[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=100
