[core]
name:gift_giver
tags:Proxy
displayText:gift_giver
maxHp:100
mass:0
price:0
copyFrom:ROOT:SPARK/SPARK.template,ROOT:unit-behaviors.template
radius:0
isBio:false

isUnrepairableUnit:true
isUnselectable:true
isUnselectableAsTarget:true
canNotBeDirectlyAttacked:true
canNotBeDamaged:true
canNotBeGivenOrdersByPlayer:true
disableAllUnitCollisions:true


[movement]
movementType:BUILDING

[attack]
canAttack:false

[graphics]
image:ROOT:shared/NONE.png

#[leg_1]
#x:0
#y:0
#
#attach_x:0
#attach_y:0
#rotateSpeed:0.2
#image_end:质量投射场.png
##image_middle:质量投射场.png
#spinRate:-0.4

[effect_1]
life:600
attachedToUnit:true
dirSpeed:-0.2
dirSpeedRandom:0.05
image:质量投射场.png
scaleTo:1.2
scaleFrom:1
fadeInTime:30
fadeOut:true
alpha:0.9
teamColorRatio:0.5
drawUnderUnits:true

[hiddenAction_create]
autoTriggerOnEvent:created
spawnEffects:1





[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=100000

[hiddenAction_die]
autoTrigger:if self.resource.time>10
deleteSelf:true

[turret_1]
x:0
y:0

[projectile_1]
life: 10
areaDamage:0
areaRadius:300
mutatorX_addResourcesAreaHit:Gift=10
mutatorX_ifUnitWithoutTags:NULLTAG
friendlyFire:only-ignoreEnemy
explodeOnEndOfLife:true
deflectionPower:-1
explodeEffect:NONE

[hiddenAction_attackGround]
autoTrigger:true
fireTurretXAtGround:1
fireTurretXAtGround_withOffset:0,0





