[core]
copyFrom:ROOT:SPARK/SPARK.template,ROOT:unit-behaviors.template

name:SPARK T1 建造者
displayText:T1 建造者
displayDescription:[建造][无法攻击][T1][陆地]\n早期的建造机器人,建造速度似乎不太快...\n没有任何武装,请小心敌人的袭击
#overrideAndReplace:builder
canRepairBuildings:true
canRepairUnits:false
autoRepair:false
buildSpeed:30s
tags:T1,Valid
radius:10
maxHp:100
price:600
mass:1000
isUnrepairableUnit:true


[graphics]
image:建造者.png
image_shadow:SHADOW:建造者.png
shadowOffsetX:4
shadowOffsetY:4
image_offsetY:0
scaleImagesTo:32
repairEffectAtTarget:CUSTOM:repair
repairEffectRate:180
repairEffect:CUSTOM:repair2



[movement]
movementType:LAND
moveSpeed:0.6
targetHeight:1
targetHeightDrift:1
moveAccelerationSpeed:0.1
moveDecelerationSpeed:0.1

maxTurnSpeed:4
turnAcceleration:8


[attack]
canAttack:false

#[turret_1]
#x:0
#y:0

[effect_repair]
life:360
showInFog:false
priority:high
attachedToUnit:true
#atmospheric:true
image:维修效果c.png
total_frames:6
animateFrameStart:0
animateFrameEnd:5
animateFrameSpeed:0.5
animateFrameSpeedRandom:0.2
animateFrameLooping:true
teamColorRatio:0.1

dirSpeed:1
dirSpeedRandom:0.3

[effect_repair2]
life:360
showInFog:false
priority:high
attachedToUnit:true
#atmospheric:true
image:圆圈.png
total_frames:1
scaleTo:3
scaleFrom:0.01
teamColorRatio:0.3
#shadow:true
hSpeed:0.01
fadeInTime:20
fadeOut:true
dirSpeed:100
alpha:0.6


[canBuild_1]
pos:1
name:T1 SPARK机器人工厂

[canBuild_2]
pos:2
name:SPARK T1资源提取器



[canBuild_3]
pos:3
name:SPARK T1对地防御塔
addResources:hp=-10000

[canBuild_4]
pos:4
name:SPARK T1防空防御塔
addResources:hp=-10000

[canBuild_9]
pos:3.5
name:SPARK T2远程火炮
addResources:hp=-10000

[canBuild_5]
pos:5
name:SPARK T1防御碉堡
addResources:hp=-10000

[canBuild_6]
pos:6
name:T1 SPARK空军工厂

[canBuild_10]
pos:6.5
name:T1 SPARK陆军工厂



[canBuild_7]
pos:7
name:石油分馏厂

[canBuild_8]
pos:8
name:SPARK 无人机控制站


[ai]
useAsBuilder:true

[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=200

[hiddenAction_resolution]
autoTrigger:if self.isControlledByAI() and numberOfUnitsInTeam(withinRange=150,greaterThan=1) and rnd(1,60)==1
alsoTriggerAction:解放




[action_解放]
text:「解放」
description:建造者解放自身以给周围单位增加「馈赠」以获得特殊效果\n-会使你失去这个建造者\n-在工厂旁边「解放」可以升级科技或加速生产\n-在单位旁「解放」可以为其回复生命值并为其提供经验值
#deleteSelf:true
#alsoTriggerAction:解放
fireTurretXAtGround:1
fireTurretXAtGround_withOffset:0,0
#
buildSpeed:1s
addResources:setFlag=31
pos:0
setUnitStats:movespeed=0
isLocked:if self.hasFlag(id=31)
deleteSelf:true

[hiddenAction_addhpByGift]
autoTrigger:false

[hiddenAction_addhpByExp]
autoTrigger:false


[hiddenAction_subHp]
autoTrigger:if self.hasFlag(id=31)
#fireTurretXAtGround:1
#fireTurretXAtGround_withOffset:0,0
addResourcesWithLogic:hp=${core.maxHp}*(-0.1)

[turret_1]
x:0
y:0

[projectile_1]
life: 10
#areaDamage:0
#areaRadius:300
#mutatorX_addResourcesAreaHit:Gift=10
#mutatorX_ifUnitWithoutTags:NULLTAG
#friendlyFire:only-ignoreEnemy
#explodeOnEndOfLife:true
deflectionPower:-1
#explodeEffect:NONE
directDamage:0
spawnUnit:gift_giver



