[core]
name              : SPARK T2远程火炮
tags:Valid
displayText:SPARK T2远程火炮

displayDescription: [建筑][对地]\n-高伤害的远程轰炸单位\n-不要将它暴露在重型单位直射火力下!\n-建造会消耗过多的质量导致建造者被摧毁,并且需要长的建造时间\n-建议大量建造者一起建造
selfBuildRate:600s

copyFrom:ROOT:SPARK/SPARK.template,ROOT:unit-behaviors.template
price:600
mass:114514
radius:13
isBio:false
isBug:false
isBuilder:false
transportUnitsKillOnDeath:false
armour:20
maxHp:2200
buildSpeed:600s

isBuilding:true
footprint:0,0,0,0
constructionFootprint:0,0,0,0

[graphics]
image:ROOT:/SPARK/SPARK防御塔/SPARK T1防御塔/STARK T1轻型炮塔基座.png
image_turret:spark T2远程火炮炮身.png
image_shadow:SHADOW:ROOT:/SPARK/SPARK防御塔/SPARK T1防御塔/STARK T1轻型炮塔基座.png
shadowOffsetX:2
shadowOffsetY:2
teamColorsOnTurret:true


[attack]
maxAttackRange:460
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
showRangeUIGuide:1

[turret_2]
x:0
y:15
slave:true
attachedTo:1
#barrelOffsetX_onOddShots:1
recoilOffset:-15
recoilOutTime:5
recoilReturnTime:60
shoot_sound:cannon_firing
delay:60
image:spark T2远程火炮炮管.png
warmup:450
size:15
shoot_flame:CUSTOM:fire

[turret_1]
x:0
y:0
canAttack:false
#idleSpin:0.2
turnSpeed:0.5


[projectile_1]
life:1000
areaDamage:800
areaRadius:50
mutatorX_ifUnitWithTags:lives
mutatorX_directDamageMultiplier:1.5
speed:3
#image:抛射体1.png
drawSize:0.65
explodeEffect:shockwave
lightSize:0.3
lightColor:#AAFFAAAA
trailEffect:CUSTOM:weiyan
trailEffectRate:1
targetGround:true
initialUnguidedSpeedY:-1
gravity:-2
targetSpeedAcceleration:-0.2
speedSpread:0.5
wobbleAmplitude:0.1
frame:3


[effect_weiyan]
life:100
image:火焰.png
attachedToUnit:false
alpha:0.5
color:#AAFF9999

[effect_fire]
life:40
image:SHARED:light_50.png
attachedToUnit:false
alpha:1
fadeOut:true
#color:#AAFF9999


[movement]
movementType:BUILDING


#[ai]
#buildPriority:0.1
#noneInBaseExtraPriority:0.53
#recommendedInEachBaseNum:5
#recommendedInEachBasePriorityIfUnmet:0.29
#maxEachBase:17

[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=800


[decal_target]
image:ROOT:/shared/at.png
layer:onTop
alpha:0.6
xOffsetAbsolute:10
yOffsetAbsolute:-10
onlyWhileAlive:true

[ai]
useAsAttacker:true
buildPriority:0.40
recommendedInEachBaseNum:10
#upgradedFrom:SPARK T1 建造者



