[core]
copyFrom:ROOT:SPARK/SPARK.template,ROOT:unit-behaviors.template


name:SPARK T2升级核心

displayText:T2升级核心
displayDescription:[无法攻击][T2][陆地]\n中期高级机器人的框架\n可以搭载小型机器人并合成成高级机器人
price:0
mass:2000
maxHp:500

radius:7
buildSpeed:50s
maxTransportingUnits:1
tags:technology,Valid
#transportUnitsBlockAirAndWaterUnits:false


[graphics]
#image:SPARK T1战斗机器人c.png
image:SPARK T2升级核心.png
scaleImagesTo:20
image_shadow:SHADOW:SPARK T2升级核心.png
image_wreak:SPARK T1战斗机器人残骸.png

shadowOffsetX:1
shadowOffsetY:1
teamColorsOnTurret:true

image_turret:SPARK T2升级核心.png
scaleTurretImagesTo:20
lock_body_rotation_with_main_turret:true

[attack]
canAttack:false
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false



[turret_1]
x:0
y:0

shoot_sound:gun_fire

recoilOffset:-2
recoilOutTime:4
recoilReturnTime:30



idleSweepSpeed:0.3
idleSweepAngle:60
idleSweepDelay:180
idleSweepAddRandomDelay:100
idleSweepAddRandomAngle:20
idleSweepCondition:if not self.isMoving()
delay:80



barrelX:5
barrelY:5

[projectile_1]
directDamage:75
life:100
frame:1
drawSize:0.7
speed:5
lightSize:0.8
lightColor:#FF882200
buildingDamageMultiplier:0.4

[movement]
movementType:HOVER
moveSpeed:0.4
moveAccelerationSpeed:0.1
moveDecelerationSpeed:0.1
targetHeight:2
targetHeightDrift:1
maxTurnSpeed:1
turnAcceleration:3
moveIgnoringBody:true

[attachment_1]
x:0
y:0
#onCreateSpawnUnitOf:SPARK指挥官附属机枪
isUnselectable:true
addTransportedUnits:true


[action_upgrade_1]
text:升级_等离子机器人
buildSpeed:20s
isVisible:if self.transportingUnitWithTags(includes="Tech1GunRobot")
convertTo:SPARK T2等离子机器人
unitShownInUI:SPARK T2等离子机器人

whenBuilding_cannotMove:true
deleteNumUnitsFromTransport:1

[action_upgrade_2]
text:升级_飞弹机器人
buildSpeed:20s
isVisible:if self.transportingUnitWithTags(includes="Tech1MissleBot")
convertTo:SPARK T2镭射机器人
whenBuilding_cannotMove:true
deleteNumUnitsFromTransport:1
unitShownInUI:SPARK T2镭射机器人
[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=500
