[core]
name:步兵模板
price:50
radius:7
buildSpeed:5s
isBio:true
mass:100
strictLevel:0
armourMinDamageToKeep:0
armour:0
techLevel:1

maxHp:100
displayText:步兵模板
tags:Tech_1,Infantry,lives,Valid
displayDescription:用于减少重复工作的模板单位
displayDescription_ja = 重複作業を減らすために使用されるテンプレートユニット

transportSlotsNeeded:1


[graphics]
image           : 步兵基座.png
image_back      : 步兵身体(c).png
image_offsetY   : -7
teamColorsUseHue: false

[attack]
canAttack:false
isFixedFiring:true
maxAttackRange:0

[movement]
movementType:LAND
moveAccelerationSpeed: 0.3
maxTurnSpeed:9
reverseSpeedPercentage:0

moveDecelerationSpeed: 0.05
moveSpeed:0.9

#[hiddenAction_不屈]
#
#autoTrigger:if self.tags(includes='不屈')


[hiddenAction_不屈_监测]
temporarilyAddTags:不屈
autoTrigger:if self.resource(type='不屈',greaterThan=0)
spawnEffects:不屈

setUnitStats: armour+=1145141919810
addResources:不屈=-1


[hiddenAction_clear]
autoTrigger:if self.resource(type='不屈',equalTo=0)
setUnitStats: armour=${core.armour}


[effect_不屈]
life:600
color:#FF000000
fadeInTime:20
fadeOut:true
alpha:0.5


[action_addMaxAttackRange]
text:增加最大射程
description:增加最大射程捏
autoTrigger:if self.hasParent()
setUnitStats:maxAttackRange=${attack.maxAttackRange}+20
isVisible:false

[action_subMaxAttackRange]
text:减小最大射程
description:增加减小射程捏
autoTrigger:if not self.hasParent() and self.hasFlag(id=5)
setUnitStats:maxAttackRange=${attack.maxAttackRange}
isVisible:false

[resource_不屈]
hidden:true


[action_hormor_1]
text:王牌步兵
description:更好的步兵
isVisible:false
autoTrigger:if self.resource(type='attackpoint',greaterThan=1) and not self.hasFlag(id=3)
addResources:setFlag=3
setUnitStats:movespeed+=1,maxAttackRange+=20,armour-=1,shootDamageMultiplier+=0.5,maxHp=${core.maxHp}*0.5
spawnEffects:1
pos:1.1


[action_hormor_2]
text:王牌陆军2
isVisible:false
description:更好的车组2
autoTrigger:if self.resource(type='attackpoint',greaterThan=0) and self.hasFlag(id=3)
addResources:attackpoint=-1
setUnitStats:hp+=5
spawnEffects:1
pos:1.2


[action_hormor_3]
text:王牌陆军
isVisible:false
description:更好的车组
autoTrigger:if self.resource(type='attackpoint',lessThan=1) and self.hasFlag(id=3)
addResources:unsetFlag=3
setResourcesWithLogic:attackpoint=0
setUnitStats:movespeed-=1,maxAttackRange-=20,armour+=1,shootDamageMultiplier-=0.5,maxHp=${core.maxHp}*2
pos:1.3

[effect_1]
image:ROOT:地球联合政府/飞机/星星.png
attachedToUnit:true
ySpeedAbsolute:-1
life:60
dirSpeed:100


[resource_attackpoint]
hidden:true

[ai]
useAsAttacker:true

[global_resource_hero]
hidden:false
