[core]
copyFrom:ROOT:SPARK/SPARK.template,ROOT:unit-behaviors.template
name:SPARK 跳蛛机甲
displayText:SPARK 跳蛛机甲

displayDescription:[机甲][对地][反装甲]\n-四足跳蛛机甲，拥有相对不错的射程和火力 \n-[迟滞]过分追求火力的代价是脆弱的护甲

mass:800
price:0
maxHp:600
radius:15
buildSpeed:80s
maxTransportingUnits:0
armour:5
transportSlotsNeeded:2
tags:mech,Valid
[graphics]
image:身体.png
dustEffect:true


[attack]
maxAttackRange:90
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
showRangeUIGuide:true

#[turret_1]
#image:坦克炮塔.png
#x:0
#y:0
#shoot_sound:missile_fire
#shoot_light:#FF000000
#recoilOffset:-3
#recoilOutTime:2
#recoilReturnTime:10
#delay:60
#
#[projectile_1]
#image:抛射体.png
#life:100
#speed:1
#directDamage:100
#color:#FFAAAAAA
#drawSize:0.5
#lightSize:1
#lightCastOnGround:true
#lightColor:#FFAA0000

[turret_2]
image:电浆炮管.png
x:0
y:10
shoot_sound:missile_fire
shoot_light:#FF000000
recoilOffset:-2
recoilOutTime:2
recoilReturnTime:120
attachedTo:1
slave:1
delay:120

[turret_1]
image:炮塔.png
x:0
y:-6
shoot_sound:missile_fire
shoot_light:#FF000000
recoilOffset:-2
recoilOutTime:2
recoilReturnTime:120
delay:180
turnSpeed:5
canShoot:false


[projectile_1]
image:抛射体1.png
life:100
directDamage:300
areaDamageNoFalloff:true
color:#FFAAAAAA
drawSize:0.5
lightCastOnGround:true
speed:18
trailEffect:CUSTOM:weiyan
trailEffectRate:1
largeHitEffect:true
lightColor:#ffff00
lightSize:0.2
buildingDamageMultiplier:0.7


[hiddenAction_initSelfExtraExp]
autoTriggerOnEvent:created
addResources:selfExtraPrice=600
[effect_weiyan]
life:100
image:火焰.png
attachedToUnit:false
alpha:0.5
color:#AAFF9999
#[animation_1]
#onActions:move

[leg_1]
x:-8
y:9
attach_x:-1
attach_y:2
endDirOffset:-45
moveSpeed:2
resetAngle:25
dust_effect:false
image_leg:脚.png
holdDisMin:1
holdDisMax:4
hardLimit:8
holdDisMin_checkNeighbours:true
favourOppositeSideNeighbours:true
estimatingPositionMultiplier:0.2
drawOverBody:false

[leg_2]
copyFrom:1
x:8
y:9
attach_x:1
attach_y:2
endDirOffset:45

[leg_3]
copyFrom:1
x:-8
y:-9
attach_x:-1
attach_y:-2
endDirOffset:-135

[leg_4]
copyFrom:1
x:8
y:-9
attach_x:1
attach_y:-2
endDirOffset:135

[leg_5]
copyFrom:1
x:-10
y:0
attach_x:-2
attach_y:0
endDirOffset:-90

[leg_6]
copyFrom:1
x:10
y:0
attach_x:2
attach_y:0
endDirOffset:90


[movement]
movementType:LAND
moveSpeed:0.5
moveAccelerationSpeed:0.1
moveDecelerationSpeed:0.1
reverseSpeedPercentage:0.4
maxTurnSpeed:3
turnAcceleration:3
moveSlidingMode:false
moveIgnoringBody:true
