[core]
name : 第七国际联络部
displayText: 第七国际联络部
displayText_ja:セブンスインターナショナル リエゾン部
price: 2000
copyFrom:ROOT:地球联合政府/建筑/建筑模板.ini,ROOT:unit-behaviors.template
mass:114514
radius:30
maxHp:4000
armour:2
displayDescription:[建筑][t2科技]\n-解锁t2科技步兵\n-获得支援技能 激励 使小范围内步兵暂时无敌
displayDescription_ja = [アーキテクチャ] [T2テクノロジー] \ n-Unlock T2テクノロジー歩兵\ n-n-botinaingサポートスキルインセンティブは、無敵の小さな範囲で歩兵を作るためのインセンティブ


isBuilding:true
footprint:-1,-1,1,1
constructionFootprint:-1,-1,1,1
energyMax:1
energyStartingPercentage:0
energyRegen:0.0002
buildSpeed:60s
tags:第七国际联络部,t2,Valid
borrowResourcesWhileAlive:hero=-1

maxTransportingUnits:1
transportUnitsCanUnloadUnits:false
transportUnitsAddUnloadOption:false
transportUnitsKillOnDeath:true
transportUnitsHealBy:1
transportUnitsBlockOtherTransports:false
transportUnitsEachUnitAlwaysUsesSingleSlot:true
transportUnitsRequireMovementType:NONE,LAND,BUILDING,AIR,WATER,HOVER,OVER_CLIFF,OVER_CLIFF_WATER
transportUnitsKeepBuiltUnits:true

[turret_1]
x:0
y:0

[projectile_1]
life:1000
unloadUpToXUnitsFromSource:1
directDamage:0

[action_1]
text:投放
description:将货舱中的单位投放至兵营旁
onlyOneUnitAtATime:true
alwaysSinglePress:true
fireTurretXAtGround:1
fireTurretXAtGround_onlyOverPassableTileOf:LAND
isLocked:if not self.transportingCount(greaterThan=0)

[action_步兵坦克]
addUnitsIntoTransport:步兵坦克
pos:1
isLocked:if self.transportingCount(greaterThan=0) or self.hasFlag(id=1)
isLockedMessage:货舱已经装满!
price:900
buildSpeed:35s
unitShownInUI:步兵坦克

[action_步兵玄武]
addUnitsIntoTransport:玄武坦克
pos:1
isLocked:if self.transportingCount(greaterThan=0) or self.hasFlag(id=1)
isLockedMessage:货舱已经装满!
price:2200
buildSpeed:30s
unitShownInUI:玄武坦克

[action_纳塔托斯]
addUnitsIntoTransport:纳塔托斯
pos:1
isLocked:if self.transportingCount(greaterThan=0) or self.hasFlag(id=1)
isLockedMessage:货舱已经装满!
price:1800
buildSpeed:40s
unitShownInUI:纳塔托斯

[action_步兵战车]
addUnitsIntoTransport:步兵战车
pos:1
isLocked:if self.transportingCount(greaterThan=0) or self.hasFlag(id=1)
isLockedMessage:货舱已经装满!
price:700
buildSpeed:30s
unitShownInUI:步兵战车

[action_liv-0]
addUnitsIntoTransport:liv-0
pos:1
isLocked:if self.transportingCount(greaterThan=0) or self.hasFlag(id=1)
isLockedMessage:货舱已经装满!
price:700
buildSpeed:30s
unitShownInUI:liv-0

[action_58式中型坦克]
addUnitsIntoTransport:58中坦
pos:1
isLocked:if self.transportingCount(greaterThan=0) or self.hasFlag(id=1)
isLockedMessage:货舱已经装满!
price:1100
buildSpeed:35s
unitShownInUI:58中坦


[action_览式坦克歼击车]
addUnitsIntoTransport:览式坦克歼击车
pos:1
isLocked:if self.transportingCount(greaterThan=0) or self.hasFlag(id=1)
isLockedMessage:货舱已经装满!
price:500
buildSpeed:10s
unitShownInUI:览式坦克歼击车






[action_hidden]
text:隐藏
description:隐藏成建筑工地,可以快速被搬迁到另一个建筑工地处
isLocked:if self.queueSize(greaterThan=0) or self.transportingCount(greaterThan=0)

isVisible:if not self.hasFlag(id=1)
addResources:setFlag=1
playAnimation:1
convertTo:隐藏建筑工地
buildSpeed:0














[animation_1]
body_0:{frame:0}
body_0.2:{frame:1}
body_0.4:{frame:2}
body_0.6:{frame:3}
body_0.8:{frame:4}
body_1:{frame:5}
body_1.2:{frame:6}
body_1.4:{frame:7}
body_1.6:{frame:8}
body_1.8:{frame:9}
body_2:{frame:10}
body_2.2:{frame:11}
body_2.4:{frame:12}

KeyframeTimeScale:50


[animation_2]
body_0:{frame:12}
body_0.2:{frame:11}
body_0.4:{frame:10}
body_0.6:{frame:9}
body_0.8:{frame:8}
body_1:{frame:7}
body_1.2:{frame:6}
body_1.4:{frame:5}
body_1.6:{frame:4}
body_1.8:{frame:3}
body_2:{frame:2}
body_2.2:{frame:1}
body_2.4:{frame:0}

KeyframeTimeScale:50


[graphics]
image:第七国际联络部.png
scaleImagesTo:60
total_frames:13


[attack]
canAttack:false
maxAttackRange:2000

[resource_不屈]
hidden:true

[movement]
movementType:BUILDING



#[ai]
#buildPriority:0.15
#noneInBaseExtraPriority:0.41
#recommendedInEachBaseNum:1
#recommendedInEachBasePriorityIfUnmet:0.3
#maxEachBase:2
#
#
[global_resource_hero]
hidden:false
#
#[placementRule_maxct]
#maxCount:0
#searchTags:t2
#cannotPlaceMessage:无法建造!
#searchTeam:own
#searchDistance:114514


[placementRule_maxct]
maxCount:0
searchTags:t2
cannotPlaceMessage:无法建造!
searchTeam:own
searchDistance:114514
