[core]
copyFrom:ROOT:地球联合政府/步兵/t1步兵基础/t1步兵基础.ini,ROOT:unit-behaviors.template
price:800,hero=1
maxHp:1000
buildSpeed:20s
name:政委
displayText:政委
displayText_ja:政治将校
displayDescription:[对地][反步兵]\n-政委拥有高超的武器使用技巧,这使得他们在战场上的活力更加凶猛\n-政委可以激励周围的步兵单位,使他们暂时不会受到敌人的伤害(唯心主义超人)\n-政委可以向周围的单位下达进攻指令,有效增强小范围内步兵的各项属性
displayDescription_ja = [Earth] [Anti-Infantry] \ N-Political Commissarには素晴らしい武器の使用スキルがあり、戦場でより激しいものになります。時間がある（理想主義者のスーパーマン）\ n政治的なコミッサーは、周囲のユニットに攻撃的な指示を発行して、小さな地域の歩兵の属性を効果的に強化することができます
tags:lives,hero,政委,Valid
energyMax:1
energyRegen:0.000416
selfRegenRate     : 1

[graphics]
image_turret:步枪(c).png
turretImageScale:0.6

[hiddenAction_点数]
text:点数
autoTriggerOnEvent:destroyed
addResources:hero=1


[attack]
maxAttackRange          : 160
canAttack               : true
canAttackFlyingUnits    : false
canAttackLandUnits      : true
canAttackUnderwaterUnits: false
showRangeUIGuide        : true
#isMelee                 : true
#meleeEngangementDistance: 100
isFixedFiring           : false

[turret_1]
x:0
y:5
shoot_sound:missile_fire
shoot_light:#FF000000
recoilOffset:-3
recoilOutTime:2
recoilReturnTime:10
delay:5
projectile:1


[projectile_1]
life:100
directDamage:20


#[turret_2]
#x:0
#y:0
#image:NONE
#shoot_light:#FF999999
#delay:10
#projectile:2
#energyUsage:1
#canOnlyAttackUnitsWithTags:Infantry

#shoot_sound:attack


[projectile_2]
life:100
directDamage:0
instant:true
convertHitToSourceTeam:true
invisible:true
explodeEffect:NONE

[turret_3]
x:0
y:0
shoot_sound_vol:0
image:NONE
delay:0
projectile:3
limitingRange:0





[projectile_3]
life:10
areaDamage:-100
areaRadius:40
friendlyFire:true
mutator1_ifUnitWithTags:lives
mutator1_addResourcesAreaHit:不屈=10


[action_1]
buildSpeed                    : 0s
text                          : 激励
description_ja:指定した範囲の兵士を一定時間無敵状態にする。
description                   : 暂时的让周围的步兵进入无敌状态(类似RA2中的铁幕)
fireTurretXAtGround           : 3
fireTurretXAtGround_withOffset: 0, 0
price                         : energy=1
iconImage:激励.png
[action_2]
text:进攻
price:energy=1
description:增加单位移动速度,攻击伤害 暂时减少血量上限
description_ja:歩兵のＨＰを50削る代わりに、移動速度を早くする。
fireTurretXAtGround:4
fireTurretXAtGround_withOffset:0,0
buildSpeed:0s
onlyOneUnitAtATime:true
iconImage:进攻.png
[turret_4]
x:0
y:0
shoot_sound_vol:0
image:NONE
delay:0
projectile:4
limitingRange:0


[projectile_4]
areaDamage:-100
areaRadius:120
friendlyFire:true
mutator1_ifUnitWithTags:lives
mutator1_addResourcesAreaHit:attackpoint=30

life:100000
speed:1000

[resource_attackpoint]
hidden:true




[hiddenAction_initResTagCount]
autoTriggerOnEvent:created
setResourcesWithLogic:UnitPrice=800, UnitRadius=${core.radius}