[core]

name: 小地堡
copyFrom:ROOT:地球联合政府/建筑/建筑模板.ini,ROOT:unit-behaviors.template
displayDescription:[建筑][可驻军]\n-由工程师建造的小型地堡\n-通常用来掩护狙击手等单位
displayDescription_ja = [建築] [守備隊になることができます] \ n-n-Small地面の城はエンジニアによって建てられました\ n-は通常、スナイパーなどのユニットをカバーするために使用されます
maxHp:400
mass:114514
price:100
radius:5
buildSpeed:10s
#此模板在"基础模板"上修改
isBuilding:true
#此代码规定建筑范围
footprint:-0,0,0,0
constructionFootprint:0,0,0,0
maxTransportingUnits:2


armour:1

[graphics]
#图像节需要设置主体图像
image:地堡.png
scaleImagesTo:35    


[attack]
canAttack:true
canAttackLandUnits:true
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
turretRotateWithBody:false
turretTurnSpeed:3
attackMovement:normal
maxAttackRange:140
shootDelay:2
isFixedFiring:false

[attachment_1]
x=0
y=0
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true

[attachment_2]
x=0
y=0
isVisible:false
isUnselectable:true
canAttack:true
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
prioritizeParentsMainTarget:true
addTransportedUnits:true
resetRotationWhenNotAttacking:true






[movement]
movementType:BUILDING
