[core]
copyFrom:ROOT:unit-behaviors.template
name          : 开局指挥中心
tags:Valid
displayText   : 开局指挥中心
displayText_ja: 司令部を開設できる。その際、初動で手に入れるユニットを選択可能だ。\n自分の得意戦術に合わせ、最初の配備部隊を決めよう。


price                : 2500
mass                 : 114514
radius               : 30
selfBuildRate        : 0.01
maxHp                : 3000
armour               : 4
displayDescription   : 可以选择一个技能以使开局获得优势
displayDescription_ja = あなたはスタートの利点を作るためにスキルを選ぶことができます
 


isBuilding:true
footprint:-1,-1,1,1
constructionFootprint:-1,-1,1,1
canRepairBuildings:true
nanoRange:240
generation_credits:5
isBuilder:true
energyMax:300
energyRegen:0
energyStartingPercentage:0
fogOfWarSightRange:2

[action_zhenCha]
text       : 先声夺人
text_ja    : 速攻偵察
description: 获得一个侦察机 快速勘探敌情
description_ja:偵察ドローンを入手し、序盤の敵動向をつかもう。戦略家向き。
spawnUnits:侦察机
alsoTriggerAction:trans
showMessageToAllPlayers:玩家选择了 先声夺人
ai_isHighPriority:true

[action_tuXi]
text       : 突袭战争
text_ja    : 招集命令
description: 获得几个基础步兵 快速获得作战能力
description_ja:何名かの歩兵を確保し、すぐに作戦能力を得る。速攻戦術が得意な方に。
spawnUnits             : t1步兵*7, t1火箭步兵*3
alsoTriggerAction      : trans
showMessageToAllPlayers: 玩家选择了 突袭战争
ai_isHighPriority      : true

[action_shuiLu]
text       : 水陆两栖
text_ja    : 海兵隊創設
description: 获得一个两栖运输艇 可以把基地搬走了!
description_ja:水陸両用車を入手し、早期に揚陸能力を得る。海上戦に向く。
spawnUnits             : 两栖运输艇
alsoTriggerAction      : trans
showMessageToAllPlayers: 玩家选择了 水陆两栖
ai_isHighPriority      : true

[action_liCai]
text       : 金钱管理
text_ja    : 緊急予算確保
description: 理一波财! 获得1500元
description_ja:戦争経済という言葉を知っているかね？$1500を獲得する。
addResources           : 1500
alsoTriggerAction      : trans
showMessageToAllPlayers: 玩家选择了 金钱管理
ai_isHighPriority      : true

[action_tr]
text       : 移动炮台
text_ja    : 移動砲台
description: 获得两个移动炮台!前期的最好防御
description_ja:野砲を積んだ機動車両を2両入手する。開幕速攻へのカウンターとして有効だ。一度展開すると積みなおせないから注意。
spawnUnits             : 移动炮台车*2
price                  : 400
alsoTriggerAction      : trans
showMessageToAllPlayers: 玩家选择了 移动炮台
ai_isHighPriority      : true

[action_rushrush]
price:600
text       : 风暴突击
text_ja    : 特殊部隊招集
description: 从总部直接获得两个风暴突击队!去恶心你的对手罢
description_ja:ゲリラだ！訓練されたゲリラだ！　突撃歩兵を招集し、敵の建設現場に梱包爆薬を投げ込んだり投げ込まなかったりしよう。
spawnUnits             : t2风暴突击队*2
alsoTriggerAction      : trans
showMessageToAllPlayers: 玩家选择了 风暴突击
ai_isHighPriority      : true

[action_buildBuild]
text       : 广修碉堡
text_ja    : 工兵隊編成
description: 获得七个工程师 最大速度插塔!
description_ja:工兵隊を編成し、陣地構築を早める。「鑿岩機20台はまだか？」
spawnUnits             : 工程师*7
alsoTriggerAction      : trans
showMessageToAllPlayers: 玩家选择了 广修碉堡
ai_isHighPriority      : true

[action_trans]
autoTrigger:false
#if self.energy==300
convertTo:指挥中心
isVisible:false





[graphics]
image:基地b.png
scaleImagesTo:60

[leg_1]
image_end:基地.png
x:0
y:0
rotateSpeed:20

[animation_1]
leg1_0:{x:0,y:0}
leg1_1s:{x:0,y:0,dir:180}
onActions:idle

[attack]
canAttack:false

[movement]
movementType:BUILDING
