[core]
name:producer
tags:Proxy
dont_load:false
displayDescription:youShouldNotFoundIt
displayDescription_ja = あなたは我慢していない
price:          10000
radius:         10
maxHp:          1500
mass:           1145141919
#================================

armour:         1
isBuilding:     false
resourceRate:   0.1
onNewMapSpawn:mapCenter_asNeutral


#================================

stayNeutral:    true
createNeutral:  false


#================================

[graphics]
image:          矿石资源.png
scaleImagesTo:  20

#================================

[attack]
canAttack:      false

#================================

[movement]
movementType:   LAND

#================================

[hiddenAction_1]
autoTrigger:true
deleteSelf:true
spawnUnits:油桶*180(neutralTeam=true,spawnChance=1,offsetRandomXY=3000,gridAlign=true,skipIfOverlapping=true)
